### ISSUE TITLE
Transaction evaluation with additional UTXO set

### ISSUE THREAD

**Issue by the-headless-ghost** [Plutonomicon/cardano-transaction-lib#1000]
I'm trying to get depending transactions into the mempool.
This should work when submitting the transactions in the proper order, but before we can submit them, we have to evaluate them.
To evaluate a transaction with UTXOs that do not exist yet, Ogmios provides the additionalUtxoSet option where we can submit non-existing inputs.
As I can see in the code, CTL does not support such evaluation yet.

This issue is related: https://github.com/Plutonomicon/cardano-transaction-lib/issues/310

**Comment by the-headless-ghost** [comment]
If you don't have time to resolve this issue, I'm willing to do this fix, but I'm not sure what the right approach is to resolve this issue. I was thinking of making an additional function next to `evaluateTxCall` or an optional parameter where we can give the additional UTxO set to the function and then add this up until the `balanceAndSignTx` functions. So when we use `balanceAndSignTx`, we can add the missing UTxO to the parameters if needed.

**Comment by klntsky** [comment]
@the-headless-ghost 
You can make `balanceAndSignTxWithAdditionalUtxos` and then define `balanceAndSignTx = balanceAndSignTxWithAdditionalUtxos mempty`.

**Comment by klntsky** [comment]
I suppose you'll actually have to create a lot of new functions that accept an additional parameter and redefine the old ones with them. That's OK.
