### ISSUE TITLE
Figure out a way to `free` CSL objects

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#102]
Unfortunately allocating memory with CSL requires us to `free` it afterwards. We might need to write some sort of pseudo garbage collector to register objects upon allocation and then free them in a monadic eliminator (e.g. `runQueryM`)

This is lower-priority and we have some time to think of the best way to approach this

**Comment by ngua** [comment]
This will probably be a real problem with testing (see #140) when a large number of transactions are generated, so we should aim to figure this out by stage 5

**Comment by klntsky** [comment]
With [WeakRefs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#using_a_weakref_object), we can tie CSL object de-allocation to JS object de-allocation. Very similar to the example by [the link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#using_a_weakref_object). We can have some sort of global timer that iterates over all weak reverences we track, and when the appropriate objects die, calls free on CSL objects

**Comment by jy14898** [comment]
It might be that wasm_bindgen already supports doing this automatically, https://rustwasm.github.io/wasm-bindgen/reference/weak-references.html, but I can't tell if that flag is supported today (and if so, where do we supply it). It led me to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry which is also useful to us however
