### ISSUE TITLE
Pack wallet extensions for E2E in a single archive

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1033]
After trying to adapt Eternl for E2E for a while, I think we should change our approach to extension data packing. Instead of packing each extension state separately, we should maintain a single archive.
One reason is that "$CHROME_PROFILE"/Default/Extension\ State is shared between the extensions, so it's hard to keep the state consistent. Another is that there is some state we want to keep that does not belong to any extension.
The settings file is going to occupy about 1.6 MB, which I think is acceptable, because my best attempt to pack Eternl separately resulted in having an archive of roughly the same size (because it stores the settings in indexeddb blob)

**Comment by amirmrad** [comment]
@klntsky I believe this was resolved in the E2E rewrite PR: https://github.com/Plutonomicon/cardano-transaction-lib/pull/1075
