### ISSUE TITLE
Time validity range upper bound inclusiveness not respected

### ISSUE THREAD

**Issue by t4ccer** [Plutonomicon/cardano-transaction-lib#1041]
Consider following minting policy (V2):
```haskell
timeTest :: ClosedTerm PMintingPolicy
timeTest =
  plam $ \_ ctx' -> unTermCont $ do
    ctx <-  pletFieldsC @'["txInfo"] ctx'
    txInfo <- pletFieldsC @'["validRange"] ctx.txInfo
    validRange <- pletFieldsC @'["to", "from"] txInfo.validRange
    upperBound <- pletFieldsC @'["_1"] validRange.to -- (1)
    pure $ pif upperBound._1 (popaque (pconstant ())) (ptraceError "Range not inclusive")
```
When using it in CTL to mint in the following way:
```purescript
mint = do
  now <- getCurrentTime
  -- Ranges are clearly inclusive
  let timeRange =
        mkInterval
          (LowerBound (Finite now) true)
          (UpperBound (Finite (POSIXTime (unwrap now + BigInt.fromInt 3600000))) true)
      constraints = mconcat
        [ mustMintValue $
            Value.singleton
              policySymbol
              ""
              1
         , mustValidateIn timeRange
        ]
      lookups = mintingPolicy policy
  buildBalanceSignAndSubmitTx lookups constraints
```
## Actual
Transaction fails with the following error:
```
Uncaught Error: ExUnitsEvaluationFailed: Script failures:
- Mint:0
  - Redeemer: (Constr fromString "0" [])
  - An error has occurred:  User error:
    The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.
  - Trace:
    1.  Range not inclusive

```
Interestingly enough if we change `validRange.to` to `validRange.from` in `(1)` transaction validates.

## Expected behavior
Transaction validates.

**Comment by t4ccer** [comment]
_Probably_ the inverse (ie. requiring non-inclusive lower bound) also doesn't work

**Comment by Luis-omega** [comment]
from the discussion on slack, citing @klntsky  : 

`look into cardano-node code, to see how is it able to reconstruct it in TxInfo`

I would take a look after I end with #1066

**Comment by Luis-omega** [comment]
update mlabs internal process : 
I can confirm that in `cardano-node/cardano-cli` no other information is added to track if a boundary is closed or open up to the point a Tx is signed, the result is then serialized and I'm a little lost in the type that is used to send the end Tx to the node (is behind various walls of type polymorphism), but my guess is that this part we don't expect more info (relevant to time boundaries) is added to the transaction.

I'm beginning to dig the code of `cardano-node/cardano-node` but right now I can't figure it out how it works (where the handlers for what are). 

Alternatively, I have dug into the code of Plutus (Contract) to see if it adds more things but I haven't found anything.

**Comment by t4ccer** [comment]
So does it mean that you literary cannot construct a transaction that will with different validity interval than `[start, finish)`? If yes, this issue needs to be moved to `plutus` repo

**Comment by Luis-omega** [comment]
I'm still not sure, I'm following the related [Plutus code](https://github.com/input-output-hk/plutus-apps/blob/feb321a9c4ed301a7bf9adb54793ab7238c4ebd0/plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs#L694) right now and I think I found a different bug related to how we process time ranges: if we had multiple time constraints we keep the last processed constraint and discard the others, I still have to test if this is true but that would be on Monday.

**Comment by Saizan** [comment]
> I'm beginning to dig the code of `cardano-node/cardano-node` but right now I can't figure it out how it works (where the handlers for what are).

Maybe you are aware of this, but here's the code that builds the validity range field of TxInfo, and it can only produce a `[start,end)` kind of range if both are finite.
https://github.com/input-output-hk/cardano-ledger/blob/2acff66e84d63a81de904e1c0de70208ff1819ea/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L206

Do note that it produces `[start,+infinity)` and `(-infinity,end]` in the other cases.

**Comment by klntsky** [comment]
> if we had multiple time constraints we keep the last processed constraint

@Luis-omega this is a UX bug, could you please make it into an issue?

**Comment by Luis-omega** [comment]
Thanks, @Saizan! that's exactly what I have been looking for. 

@t4ccer I think you are right in that this must be mentioned, at least to avoid future reports of this in CTL. 

@klntsky  done #1124

**Comment by klntsky** [comment]
@Luis-omega could you please also mention this issue in the `doc/faq`

**Comment by klntsky** [comment]
Then we can close this issue.

**Comment by t4ccer** [comment]
We could also change CTL's Interval type to disallow creation of time ranges that can't appear onchain, with some explanation. It'll diverge from Plutus type though

**Comment by Luis-omega** [comment]
well, that's not the case, both `[1,10]` and `[1,11)` are the same interval (in terms of integers contained inside). I think maybe a compile time `Warning` and documentation should be better. 

Something like this for the `warning` : 

```
mkInterval lower@(LowerBound x isLowerClosed) upper@(UpperBound y isUpperClosed) =
 .
 .
 .
 if not isLowerClosed || isUpperClosed then 
    buildIntervalWithWarring lower upper 
 else 
    ...

buildIntervalWithWarring :: Warn (Text `Be aware that on-chain we can only have finite intervals of the form [lower, upper), and we would translate your interval to an equivalent interval of this form`) . 
```

**Comment by t4ccer** [comment]
Yeah, I know that these intervals are equivalent if they are over integers, but they have different onchain representation, so you can shoot yourself in a foot by designing a protocol that will expect time interval that cannot appear onchain(like the example one in the issue)

**Comment by klntsky** [comment]
> We could also change CTL's Interval type to disallow creation of time ranges that can't appear onchain, with some explanation. It'll diverge from Plutus type though

@t4ccer this is a very good idea, thanks! I think this is the way to go

**Comment by Luis-omega** [comment]
I going to take care of it as part of #1125 then.
