### ISSUE TITLE
Change Contract interfaces to support multi-address

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1045]
Initially our interfaces were designed for single-address wallets, but with addition of Eternl we need to pass all the addresses we get from the wallets.

**Comment by Luis-omega** [comment]
Does this include changes in `KeyWallet` to support multiple addresses? I'm thinking of taking this once I'm done with my two pending tasks (#974 and #1041)

**Comment by klntsky** [comment]
@Luis-omega what changes do you think are needed for KeyWallet? I think it is fine as is.

**Comment by Luis-omega** [comment]
I was thinking of supporting multiple addresses in `KeyWallet` but thinking on it, that's something different. 

I plan to begin to work on this now, to make it clear : 

- This is includes modifying functions like  : 

`Contrac.Adress.getWalletAddress  :: forall (r::Type) . Contract r (Maybe Adress)` 

to 

`Contrac.Adress.getWalletAddress  :: forall (r::Type) . Contract r (Array Adress)`

I know some of the functions that could return an `Array Adress`, all of those are part of CIP-30, are those the only ones or should I also look for other functions?

**Comment by klntsky** [comment]
@Luis-omega KeyWallet itself supports (and should support) only one address. We are only talking about CIP-30 things. Do not modify KeyWallet.
