### ISSUE TITLE
Bech32 to address

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1054]
Add `Contract.Address.addressWithNetworkTagFromBech32 :: String -> Maybe AddressWithNetworkTag` and `Contract.Address.addressFromBech32 :: String -> Contract r (Maybe String)`. The latter should assert that the network tag corresponds to the contract environment network id.

**Comment by pb99u069** [comment]
Is the type signature for the snd function correct? given the function name, shouldn't it return an `Address`
