### ISSUE TITLE
Native Script as Minting Policy / `MintingPolicyNotFound`

### ISSUE THREAD

**Issue by codybutz** [Plutonomicon/cardano-transaction-lib#1056]
I am experiencing an unexpected error when trying to mint a token using a Native Script.

For example, I am trying to mint a token using a Native Script with a TimelockExpiry condition. See example: https://github.com/codybutz/ctl-examples/tree/minting-policy-issue You can run the example with `nix build .#checks.x86_64-linux.ctl-scaffold-plutip-test -L`

You will see that we get the following error:
```
Uncaught Error: (MintingPolicyNotFound (MintingPolicyHash (ScriptHash 51ccadf8b63ad3483381586afd8ff2e140fa54d28333b99fc3fcaaf3)))
```
I believe that this is because the lookup requires that a plutus script to be included with a minting policy. However, not all minting policies are Plutus Scripts. See https://github.com/Plutonomicon/cardano-transaction-lib/blob/7921daeda855f8822b678d44fe46ffd37e0f860c/src/Types/ScriptLookups.purs#L836 and https://github.com/Plutonomicon/cardano-transaction-lib/blob/7921daeda855f8822b678d44fe46ffd37e0f860c/src/Types/ScriptLookups.purs#L995

Is it intended that all minting policies in the CTL require the use of Plutus Scripts or can we change the interface to allow for native script tokens?

**Comment by klntsky** [comment]
Thank you for reporting!
Yes, we can change the interface. In fact, we should.
