### ISSUE TITLE
Support StakeValidators in TxConstraints & balancing

### ISSUE THREAD

**Issue by t1lde** [Plutonomicon/cardano-transaction-lib#1060]
We need support for StakeValidators to implement a delegated-to StakeValidator that is used with the withdrawing-zero case. Currently, the `TxConstraints` APIs don't have any support for transactions which use StakeValidators (only the staking addresses). 

###  Possible Workaround by setting fields in UnattachedUnbalancedTx

It seems like we would be able to manually set the withdrawals, redeemers & scripts fields in the UnattachedUnbalancedTx, and Ogmios would handle the heavy-lifting in balancing afterwards? 
Is there anything else required to make StakeValidators work with `balanceTx`?

### APIs needed for withdrawing-zero StakeValidator

- A `MustWithdraw` or similar constraint (+ ScriptLookups)
- extra (does Ogmios have what we need for this?)
- we can get away without support for `Certificates`, as we can submit the other necessary transactions once with cardano-cli

### APIs needed for other uses of StakeValidator

- A `MustUseCertificate`, or similar constraint
  - Or more specific TxConstraint variants for De/Register & Delegate 
- Querying for a rewards account balance

**Comment by t1lde** [comment]
An API Sketch: https://gist.github.com/t1lde/3a649bd4f54a582749c5f6edecd3236b

**Comment by t1lde** [comment]
[our workaround so far](https://gist.github.com/t1lde/27d3ba743663cabd8b79d35df86bb378) (from @newton-migosi).

the withdrawal & register cases both fail currently - due to missing redeemers (logs attached). I *think* this just needs to copy more of what MustMintValue does.

registration is tricky, as it would seem that the balancing needs to account for the registration deposit in the total transaction balance.

**Comment by klntsky** [comment]
Thank you @t1lde ! This sketch as well ass as an example code would probably be enough for us to start working on it right away! Your help is highly appreciated

**Comment by klntsky** [comment]
## PubKey

[x] `mustRegisterStakePubKey :: forall i o. StakePubKeyHash -> TxConstraints i o`
[x] `mustDelegateStakePubKey :: forall i o. StakePubKeyHash -> PoolPubKeyHash -> TxConstraints i o`
[x] `mustWithdrawStakePubKey :: forall i o. StakePubKeyHash -> TxConstraints i o`
[x] `mustDeregisterStakePubKey :: forall i o. StakePubKeyHash -> TxConstraints i o`

## Stake Scripts (Native, Plutus)

[x] `mustRegisterStakeScript :: forall i o. StakeValidatorHash -> TxConstraints i o`

## Plutus Stake Script

[x] `mustDeregisterStakePlutusScript :: forall i o. PlutusScriptStakeValidator -> Redeemer -> TxConstraints i o`
[x] `mustDelegateStakePlutusScript :: forall i o . PlutusScriptStakeValidator -> Redeemer -> PoolPubKeyHash -> TxConstraints i o`
[ ] `mustWithdrawStakePlutusScript :: forall i o. PlutusScriptStakeValidator -> Redeemer -> TxConstraints i o` - blocked by Ogmios

## Pools

[x] `mustRegisterPool :: forall i o. PoolRegistrationParams -> TxConstraints i o`
[x] `mustRetirePool :: forall i o. PoolPubKeyHash -> Epoch -> TxConstraints i o`

**Comment by newton-migosi** [comment]
will we also get the accompanying query functions? something like [`cardano-cli query --stake-address-info`](https://github.com/input-output-hk/cardano-node/blob/0e11afc07f7c5939d291d56e6bd1abd62439ad63/doc/reference/cardano-node-cli-reference.md) which _gets the current delegations and reward accounts by stake address_

**Comment by klntsky** [comment]
@newton-migosi yes.
I plan to implement `delegationsAndRewards`, `poolIds` and `poolParameters` queries from ogmios:

https://ogmios.dev/mini-protocols/local-state-query/
