### ISSUE TITLE
Affjax request never times out because plutip-server closes the port before the stop-request

### ISSUE THREAD

**Issue by marijanp** [Plutonomicon/cardano-transaction-lib#1063]
When executing many contracts either in parallel or sequential using `withPlutipContractEnv`, for some reason `plutip-server` closes the port it serves on even before terminating. Therefore this `Affjax` request, which does not have a timeout is stuck forever and my tests don't terminate.

I'm able to verify that `plutip-server` and all the cluster nodes are still running, and I was able to trace the issue down to this piece of code.

There are two solutions:
1. figure out why the port is closed before `plutip-server` terminates
2. add a timeout to the Affjcax request trying to stop the cluster gracefully. If it times out, kill it and ignore errors.

https://github.com/Plutonomicon/cardano-transaction-lib/blob/a0fdde6fd2c0b2576918bcf0c1d0f9ded22d229a/src/Plutip/Server.purs#L310-L334

**Comment by klntsky** [comment]
Seems like it is not happening anymore? Reopen if it is
