### ISSUE TITLE
Choose a consistent error-handling approach

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#107]
Things have started to get a bit complex w.r.t error handling (e.g. "pyramid-of-doom"-style pattern matching on various `Maybe`s and `Either`s). We should pick a single strategy for dealing with this inside `QueryM`, which would allow us to simplify quite a bit

Two possible options:
- add `ExceptT` to the `QueryM` stack
- make `QueryM` an instance of `MonadThrow` (after newtyping it) and throw/catch impure exceptions as necessary

**Comment by ngua** [comment]
I am personally partial to option two -- but this is probably because I am used to this strategy in Haskell where `ExceptT` prevents one from using a lot of nice concurrency features

I would be fine with either of the two solutions above though. Any other ideas?

**Comment by klntsky** [comment]
@ngua do you mean `MonadError`? 

I'd vote for 2, since that would allow us to handle underlying `Aff` errors and our domain errors uniformly.

**Comment by adamczykm** [comment]
> I am used to this strategy in Haskell where `ExceptT` prevents one from using a lot of nice concurrency features
Can we expand on this subject? Do you have any reference materials? I haven't worked with ExpectT and concurrency yet and would like to avoid any pains in the future :)

**Comment by adamczykm** [comment]
What do you think about this library?
https://pursuit.purescript.org/packages/purescript-checked-exceptions/1.0.0

**Comment by ngua** [comment]
We should take care of this soon. The various `Maybe`s, `Either`s, etc... are inconveniencing library users
