### ISSUE TITLE
Complete CTL Test Plan Coverage

### ISSUE THREAD

**Issue by MitchyCola** [Plutonomicon/cardano-transaction-lib#1080]
## CTL Test Plan Progress
This issue will be used to track the progress of the CTL Test Plan coverage.

Please link PRs when adding coverages. Make sure to update [doc/test-plan.md](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md).

### Constraints/lookups
Each of the following constraints should be covered, along with the lookup that it implies (indicated where applicable):
- [x] `mustSpendPubKeyOutput` https://github.com/Plutonomicon/cardano-transaction-lib/pull/1024
  - **Note**: This constraint is included in our stake key integration with Plutip. We should still write a full contract that uses it
- [ ] `mustBeSignedBy` https://github.com/Plutonomicon/cardano-transaction-lib/pull/1101
  - **Note**: This constraint is also included in our Plutip stake key integration, as with `mustSpendPubKeyOutput`
  - **Relevant issue**: https://github.com/Plutonomicon/cardano-transaction-lib/issues/569
- [ ] `mustHashDatum`
- [x] `mustIncludeDatum` https://github.com/Plutonomicon/cardano-transaction-lib/pull/1087
- [x] `mustProduceAtLeastTotal`. Also implies:
  - [x] `mustProduceAtLeast`
- [x] `mustSatisfyAnyOf`
- [x] `mustSpendAtLeastTotal`. Also implies:
  - [x] `mustSpendAtLeast`
- [ ] `mustValidateIn` https://github.com/Plutonomicon/cardano-transaction-lib/pull/1101

In addition, several redeemer combinations in a **single transaction** must be covered:
- [x] Two or more `Spend` redeemers
- [x] (At least) One each of a `Spend` and `Mint` redeemer

### Unit and integration testing
Currently, we require parsing tests for the following data structures:
- `ogmios-datum-cache`
  - [x] `GetDatumsByHashesR` https://github.com/Plutonomicon/cardano-transaction-lib/pull/408 https://github.com/Plutonomicon/cardano-transaction-lib/pull/959
  - [x] `GetTxByHashR`

**Comment by klntsky** [comment]
Done
