### ISSUE TITLE
Add `logLevel` parameter to `customLogger` in `ConfigParams`

### ISSUE THREAD

**Issue by rmgaray** [Plutonomicon/cardano-transaction-lib#1084]
I was trying to filter out messages of a certain log level while using a custom logger. Unexpectedly, no filtering occurred at all.

After asking around on Slack about this, @Luis-omega identified the culprit:

```config # _.customLogger >>> fromMaybe (logWithLevel config.logLevel)```

https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/src/Internal/QueryM.purs#L325

When a `customLogger` is set, the `logLevel` is not used for filtering. I think this behaviour is a bit unintuitive and we should document it, at least.

**Comment by Luis-omega** [comment]
I think we should also document if `suppressLog` works even with a `customLogger` or not.

**Comment by klntsky** [comment]
`customLogger` accepts a `Message` and it can filter based on `logLevel` field of the message. It should implement the logic by itself.

**Comment by klntsky** [comment]
Come to think of it, we can add one more parameter to customLogger (a logging level), and pass it from the config.

**Comment by pb99u069** [comment]
@klntsky I'm not sure if I got this idea correctly. Do you mean to move the `LogLevel` out of the `Message` type used for the `customLogger` into the `ConfigParams` type? Because if I just add another LogLevel for the `customLogger` they would conflict each other, no?
