### ISSUE TITLE
Consider removing `mustIncludeDatum` constraint

### ISSUE THREAD

**Issue by pb99u069** [Plutonomicon/cardano-transaction-lib#1089]
I couldn't find a scenario where the `mustIncludeDatum` constraint is needed (see this [PR](https://github.com/Plutonomicon/cardano-transaction-lib/pull/1087)), so if there really is none we should maybe consider removing it

**Comment by errfrom** [comment]
One may want to use `mustIncludeDatum` to have some backup in case the ODC request fails for some reason https://github.com/Plutonomicon/cardano-transaction-lib/blob/1999bb962141ffea09767f299a5759420097d189/src/Internal/Types/ScriptLookups.purs#L965-L971

**Comment by klntsky** [comment]
Since it will fail for any datum that is not on-chain, it's the only way to use a new datum.
