### ISSUE TITLE
document how to set up private testnet infrastructure locally

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-transaction-lib#11]
the docs now include public testnet infra, but not private.  since this library will ultimately need to serve both the front end integration as well as E2E testing, we should probably document how to use the library with the Cardano Wallet Backend as well.

**Comment by Benjmhart** [comment]
update: this should now be nix-shell scripts i guess?

**Comment by ngua** [comment]
I didn't realize this was still open. We've supported connecting to private testnets for a while now
