### ISSUE TITLE
Expose BigNum in Contract

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1107]
Add `Contract.Numeric.BigNum` module, re-export everything that is related to BigNum

**Comment by klntsky** [comment]
Must have for stake support - some of the parameters used to register stake are bignums

**Comment by pb99u069** [comment]
@klntsky should I change the import statements from `Ctl.Internal.Types.BigNum` to `Contract.BigNum` in our tests (like f.ex. [here](https://github.com/Plutonomicon/cardano-transaction-lib/blob/5f9bd3b8550af7ff6ffa9b23848142a7e700b217/test/Serialization.purs#L12)) as well or is this not matter?

**Comment by klntsky** [comment]
@pb99u069 It's better to change imports in the tests, because the users are likely to look at them and copy-paste.
