### ISSUE TITLE
Make `Contract` query backend configurable 

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1119]
Make `Contract` runtime and `ConfigParams` parametrize-able with a backend. Move every query layer function to a handle (as in *handle pattern*):

```purescript
type QueryHandle = 
  { getChainTip :: Aff ChainTip
  , getDatumByHash :: DatumHash -> Aff Datum
  ...
  }
```

Particular handle contents are TBD. Please pay close attention to this description: https://github.com/Plutonomicon/cardano-transaction-lib/issues/524 - it should highlight what is required to be in the handle. In particular, note that we use `EraSummaries` ogmios endpoint in `QueryM` for time conversions (`slotToPosixTime`, `posixTimeToSlot`), so we should expose only these functions in the handle, and not the whole `eraSummaries`.

---

`QueryM` monad should be either removed or used only for Ogmios/ODC/ctl-server backends, and Contract should contain a reference to a handle instead. `ConfigParams` should be changed: we should include a `type BackendSpec { ctlServer :: Maybe _, queryBackend:: QueryBackend }` where `data QueryBackend = CtlRuntime { ... } | BlockfrostRuntime {..}`

We want a function of type `QueryBackend -> Aff QueryHandle` (attempt to use it with `BlockfrostRuntime` should throw an error until Blockfrost backend is implemented).

**Comment by Luis-omega** [comment]
Is there something more that I must know about it? I would like to take it.
