### ISSUE TITLE
Implement query stubs for blockfrost backend handle.

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1120]
Implementation of Blockfrost query backend should be done in parallel by multiple developers. Implement query stubs for blockfrost backend handle that will be created in #1119

**Comment by uhbif19** [comment]
@klntsky Do this need something more than just record with `undefined` in fields? Or with undefined in functions in separate file?

It seems to me like proper stub will be hard to make work with integration tests, and I do not understand what may be other needs for it.

**Comment by errfrom** [comment]
@klntsky @uhbif19 I too don't understand what is the point of writing query stubs when we can already proceed to implementing the actual queries.
