### ISSUE TITLE
Constraints solver ignores multiple time contraints 

### ISSUE THREAD

**Issue by Luis-omega** [Plutonomicon/cardano-transaction-lib#1124]
Our current approach to solving time constraints is to set the time to the interval given in the constraint ignoring previous values, this means that the end result contains the interval of the last processed constraint. 

To show it you can run the following contract : 

```
contract :: Contract () Unit
contract = do
  logInfo' "Running Examples.MultipleTimeConstraints"
  now <- currentTime
  let
    timeRange1 =
        mkInterval
          (LowerBound (Finite now) true)
          (UpperBound (Finite (POSIXTime (unwrap now + BigInt.fromInt 3600000))) true)
    timeRange2 =
        mkInterval
          (LowerBound (Finite (POSIXTime (unwrap now + BigInt.fromInt 8000000))) true)
          (UpperBound (Finite (POSIXTime (unwrap now + BigInt.fromInt 8000000))) true)
    constraints1 :: Constraints.TxConstraints Void Void
    constraints1 = Constraints.mustValidateIn timeRange1

    constraints2 :: Constraints.TxConstraints Void Void
    constraints2 = Constraints.mustValidateIn timeRange2

    constraints3 :: Constraints.TxConstraints Void Void
    constraints3 = constraints1 <> constraints2


    lookups :: Lookups.ScriptLookups Void
    lookups = mempty

  unbalancedTx1 <- liftedE $ Lookups.mkUnbalancedTx lookups constraints1
  unbalancedTx2 <- liftedE $ Lookups.mkUnbalancedTx lookups constraints2
  unbalancedTx3 <- liftedE $ Lookups.mkUnbalancedTx lookups constraints3

  let getTimes :: UnattachedUnbalancedTx -> Maybe Slot /\ Maybe Slot
      getTimes utx = let body = unwrap (((unwrap (unwrap ((unwrap utx).unbalancedTx)).transaction)).body)
                      in 
                       body.validityStartInterval /\ body.ttl

  logInfo' "unbalanced1"
  logInfo' $ show $ getTimes unbalancedTx1
  logInfo' "unbalanced2"
  logInfo' $ show $ getTimes unbalancedTx2
  logInfo' "unbalanced3"
  logInfo' $ show $ getTimes unbalancedTx3
```

The result is : 

```
[INFO] 2022-10-17T18:52:44.610Z unbalanced1
output.js?ee2e:10297 [INFO] 2022-10-17T18:52:44.610Z (Tuple (Just (Slot fromString "6029545")) (Just (Slot fromString "6033146")))
output.js?ee2e:10297 [INFO] 2022-10-17T18:52:44.610Z unbalanced2
output.js?ee2e:10297 [INFO] 2022-10-17T18:52:44.610Z (Tuple (Just (Slot fromString "6037545")) (Just (Slot fromString "6037546")))
output.js?ee2e:10297 [INFO] 2022-10-17T18:52:44.610Z unbalanced3
output.js?ee2e:10297 [INFO] 2022-10-17T18:52:44.611Z (Tuple (Just (Slot fromString "6037545")) (Just (Slot fromString "6037546")))
```

In this particular case, we expected some error to be triggered at the last `transaction` as is not possible to solve both time constraints.

**Comment by Luis-omega** [comment]
Also, I think we should change 

`mkInterval :: forall (a :: Type). LowerBound a -> UpperBound a -> Interval a`  

To 

`mkInterval :: forall (a :: Type). LowerBound a -> UpperBound a -> Maybe (Interval a)`

And enforce its use as a smart contract instead of exporting the constructor for `Interval`. I know this would be an API change, but allowing users to construct malformed intervals sounds bad.

**Comment by klntsky** [comment]
@Luis-omega I agree, more type-safety is always an improvement. Please implement that change as part of your PR.

**Comment by Luis-omega** [comment]
With this change it makes sense to separate `NonEmpty` intervals from `EmptyIntervals` I have been thinking of three options : 

- Introduce a new constructor for `Interval` only for `EmptyIntervals`, this broke the `Newtype` instance and all that depends on it (a good thing since one can build an interval using `wrap`), but I'm unsure about how to change the `ToData` instance. 
- Do as before but introduce a new type named `PlutusInterval` for internal use with the same properties as the current `Interval` and just translate `Interval` to `PlutusInterval` to obtain for free the needed instances. 
- Add a new type `NonEmptyInterval` and encourage its use as much as we can. 

The easier one is the second one as it would avoid the possible bugs of rewriting the instances (and save us the work of doing it) but I see it as a lazy option.

**Comment by Luis-omega** [comment]
Details about why we need this change : 

- Our current approach allows having an infinite number of different `empty intervals` like `[10,1]` and `[20,1]`. 
- The `Eq` instance for `Interval` is derived using `Newtype` this means that `[10,1]==[20,1]  = false` 
- We have a canonic way to get an `empty interval` using the `never` function, but we can also get a lot of different `empty intervals` using the `meet` function of the `MeetSemilattice` and maybe with other functions. 

Another option would be to just return `Maybe (Interval a)` instead of `Interval a` in a lot of functions in case the interval is empty, but this would mean that : 

- User cannot represent an `empty interval` 
- We mustn't have a `MeetSemilattice` instance (and maybe others), as we cannot represent the `empty interval` 
- Introduction of more breaking API changes. 
-
