### ISSUE TITLE
Remove nix code form doc/runtime.md

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1147]
Instead of putting effort to keep it in sync with the template project, we can comment the `template/ctl-scaffold/flake.nix` file itself and only list what is possible to achieve in the docs, pointing to the code.

NB: the `runtime.md` file exists because it was created before we added ctl-scaffold template

**Comment by pb99u069** [comment]
forgot to link it. issue was solved with https://github.com/Plutonomicon/cardano-transaction-lib/pull/1168
