### ISSUE TITLE
Add whitespace checks to syntax checks

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1162]
We should add a formatting check that disallows:

- whitespaces at the end-of-line: `grep -rn ' $'`
- extra newlines at the end-of-file (only one should be present).

These should go to the makefile and included as dependencies into the `check-format` command

**Comment by uhbif19** [comment]
Seems like viable solution, if external dependencies are okay: https://nklya.medium.com/hot-to-linter-basic-things-like-trailing-whitespaces-and-newlines-7b40da8f688d

**Comment by klntsky** [comment]
@uhbif19 `.editorconfig` is a good idea, however, we also need CI checks. The github actions from this article are, IMO, too heavy/complicated, besides, we should use nix-powered checks in CI if possible (we only make an exception for link live-ness checker, because it'd be hard to implement the same thing in Hydra).

The easiest way would be to add a few grep-based commands to `Makefile`'s `check-format`.

**Comment by uhbif19** [comment]
@uhbif19 `editorconfig-check` is available at nixpkgs. It works slow through, probably that is because of >30k errors.

**Comment by uhbif19** [comment]
Bash solution in my PR uses few seconds to check for endlines in end-of-flle. Maybe some non-bash solution might perform better.
