### ISSUE TITLE
mustPayToPubKeyAddress should accept a Credential instead of a StakePubKeyHash

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1173]
Currently it's impossible to represent an address that consists of a payment pubkey hash and a script hash.

**Comment by klntsky** [comment]
Making it blocked because we need to rethink the constraints interface issues all at once.

**Comment by klntsky** [comment]
#1533 - will be redesigned entirely

**Comment by errfrom** [comment]
Reopening since some projects still rely on the legacy tx constraints interface, and the issue seems relatively easy to fix.
