### ISSUE TITLE
clean up temporary directory when exiting with ctrl+c

### ISSUE THREAD

**Issue by pb99u069** [Plutonomicon/cardano-transaction-lib#1176]
This [PR](https://github.com/Plutonomicon/cardano-transaction-lib/pull/1144) cleans up the temporary postgres databaseDir. But this doesn't work when we exit Plutip tests with ctrl+c.

**Comment by klntsky** [comment]
This is because onExit handler is skipped in nodejs when the signal is SIGINT (the one terminal sends with ctrl+c).

https://stackoverflow.com/questions/21864127/nodejs-process-hangs-on-exit-ctrlc

We should add a listener for SIGINT as well to the main process

**Comment by klntsky** [comment]
This is the relevant funciton in purescript: https://pursuit.purescript.org/packages/purescript-node-process/10.0.0/docs/Node.Process#v:onSignal
