### ISSUE TITLE
`ArbitraryUtxoDistr` doesn't generate `Array` `UtxoDistribution`

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#1187]
https://github.com/Plutonomicon/cardano-transaction-lib/blob/09174df2de288cb27e001cc437281d362024db90/test/Plutip/UtxoDistribution.purs#L129-L133

Naively we might try adding `UDArray (Array UtxoDistribution)` to the constructors, however it would not be type safe, as the array needs to be homogenous in the distribution type. This might require complex type indexing and/or existentials, however.

**Comment by klntsky** [comment]
This is very low priority I think. What safety properties can we potentially leave behind? There's a very high chance that if it works for some cases it will work for all. The `UtxoDistribution` machinery is just a fancy way of forming type-safe plutip-server HTTP requests.

**Comment by klntsky** [comment]
I also think this test suite could've been just a few test cases, but since there's an `Arbitrary`-based generator already, let's just keep it that way.

**Comment by jy14898** [comment]
I think after my plutip PR we're safer, but I had to fix a bug where array utxo distributions didn't work when composed with other distributions. It would have been caught if it had been included in these tests, and it's not immediately obvious it didn't test arrays from the test names.

I mostly made this issue to track the note I made in my PR about there being no arbitrary array utxo distributions - I agree we're better off with unit tests
