### ISSUE TITLE
E2E+Plutip: Do not connect to the services on nodejs side

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1197]
In E2E+Plutip integration, a new connection to all the services [is established](https://github.com/Plutonomicon/cardano-transaction-lib/blob/229cbd471834e3ccc009aee43a3d5f2da055ba8c/src/Internal/Test/E2E/Runner.purs#L222) on nodejs side (just because it's simpler to do that due to easy code reuse), but it's not actually used.

We need to decide if it's worth implicitly checking the connection on the nodejs side and if not, remove it.

blocked by #1196

**Comment by rynoV** [comment]
> but it's not actually used

I don't believe this is accurate, as the connections to the services are used [to initialize the wallets](https://github.com/Plutonomicon/cardano-transaction-lib/blob/886e90fb6ab9233d73d793fb4b60fbba8d62491e/src/Internal/Plutip/Server.purs#L385). cc @klntsky

**Comment by klntsky** [comment]
@rynoV yes, you are right, my bad.
