### ISSUE TITLE
untagged union based functions vs. multiple imported functions vs. type classes

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-transaction-lib#120]
Let's discuss. Below is an original comment that started the issue.

> Use `toBytes` from `Serialization` here and below. No need to multiply functions like this.

_Originally posted by @klntsky in https://github.com/Plutonomicon/cardano-browser-tx/pull/111#discussion_r807819532_

**Comment by adamczykm** [comment]
Lots of classes in cardano-serialisation-lib expose similar interfaces, for example `.to_bytes()` functions. Currently part of bindings use an approach where the dynamic nature of JS is used and the function is then imported as if it worked on an untagged union. This way we can provide `to_bytes()` function binding only once and for all types that support them. The downside is that it can't be called directly but only after a cast to the untagged union i.e. `asOneOf`.
The other approach it to more closely follow the serialisation library and create functions for each actual JS function being called, which is also used in `Serialisation.Address` module. It makes less assumptions about the future structure of the serialisation library. But produced more functions and names.
Finally, the first approach can be extended with adding typeclasses that'd automatically call untagged union conversion which would get as back with the amount of the code, but the convenience of usage would be better. The third option is therefore in its essence only name overloading. Many people think that using typeclasses for such thing is the mechanism abuse.
What are your preferences?

**Comment by klntsky** [comment]
> The downside is that it can't be called directly but only after a cast to the untagged union i.e. asOneOf.

This is true for this particular implementation, but not so true for this approach in general. For example, in [one of my personal projects](https://github.com/klntsky/purescript-playwright/blob/3638634ae1e77c30ab557f959de43952862e6f13/src/Playwright.purs#L91) I implemented open union interfaces with `Castable` from untagged-union, removing the need to call `asOneOf`.

When we want to get values out of FFI and we need to dispatch based on type information, then we'd still need typeclasses.

**Comment by adamczykm** [comment]
Do you think that it would be beneficial if we decided on a common approach here?

**Comment by klntsky** [comment]
I propose this:

If we need to pass values to FFI, `untagged-union` with a type variable and `Castable` constraint on it.
If we need to get values out of FFI, type classes.

**Comment by klntsky** [comment]
No more important to us, the code has already been written.
