### ISSUE TITLE
Improve trailing whitespace check performance.

### ISSUE THREAD

**Issue by Luis-omega** [Plutonomicon/cardano-transaction-lib#1212]
Given how fast formatting all files could be, I'm surprised at how long it can take the current check of trailing whitespace (the slower It has run is around 5 seconds in my pc).

**Comment by klntsky** [comment]
Is your revision after this change or before?  https://github.com/Plutonomicon/cardano-transaction-lib/commit/4758a429d830a2b4dea95ec552bd7da8c06f754c

**Comment by jy14898** [comment]
It's slow for me too, although it's actually the newline check. It unfortunately goes through all the generated files in ctl-scaffold, as well as those in server. They account for 244 of the 651 files find discovers before executing further checks via exec (which will be slow)

**Comment by klntsky** [comment]
I see. The problem is build artifacts in `server/`, right?

So "the ask" of this issue should be: include only the sources in `server` directory, not the whole dir.

**Comment by jy14898** [comment]
Not only the server, but the template/ctl-scaffold needs to be treated the same way the base of the repo is. `.spago2nix` for example is not excluded
