### ISSUE TITLE
Add E2E tests with Plutip+CIP30Mock to CI

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1213]
1. Find out how to bundle and serve the examples in CI (normally done with `make run-dev` from nix shell on developers' machines). We should run the server in background and kill when the tests end
2. create a separate test suite file (like `test/e2e.env`) that only includes Plutip+Cip30Mock tests
3. Run the test suite in a separate nix check.

We probably want to make `chromium` required in default.nix at this point to actually use it in Hydra

**Comment by jy14898** [comment]
Is this a duplicate of https://github.com/Plutonomicon/cardano-transaction-lib/issues/1205?
