### ISSUE TITLE
Investigate if we should connect Kupo to Ogmios or cardano-node

### ISSUE THREAD

**Issue by errfrom** [Plutonomicon/cardano-transaction-lib#1226]

**Comment by klntsky** [comment]
Arguments for cardano-node: 
- it's faster (as claimed by Matthias)
- Ogmios will become optional
Arguments for Ogmios: 
- TBD

**Comment by jy14898** [comment]
One possible argument for Ogmios is it may help with situations where tx's are submitted to ogmios but kupo isn't yet aware of them. This is purely hypothetical

**Comment by klntsky** [comment]
Direct connection to cardano-node seems to work well and we haven't observed any problems with that.
