### ISSUE TITLE
Replace ODC with Kupo for its core functionality

### ISSUE THREAD

**Issue by errfrom** [Plutonomicon/cardano-transaction-lib#1234]

**Comment by jy14898** [comment]
Without support for getting whole transactions by hash, Kupo can't replace ODC in its entirety. What's the plan with regards to that?

**Comment by klntsky** [comment]
@jy14898 we can drop tx-by-hash from the API (actually we only need to check for transaction presence in awaitTxConfirmed, we do not need to get the contents).

We can do that using https://cardanosolutions.github.io/kupo/#operation/getMetadataBySlot - query for first slot of every block before the chain tip continuously
