### ISSUE TITLE
`findSettingsArchive` uses incorrect option

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1254]
https://github.com/Plutonomicon/cardano-transaction-lib/blob/bc72eaa53b44abec0480555483db2082fa526f81/src/Internal/Test/E2E/Runner.purs#L618

It should be `testOptions.settingsArchive`

**Comment by jy14898** [comment]
Fixed in https://github.com/Plutonomicon/cardano-transaction-lib/pull/1253
