### ISSUE TITLE
Rewrite purescript-aeson as a wrapper over json-bigint

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1258]
https://github.com/mlabs-haskell/purescript-aeson/issues/11
https://www.npmjs.com/package/json-bigint

**Comment by jy14898** [comment]
I'd actually avoid the npm version of json-bigint. The maintainer hasn't released a version in 2 years. Ogmios made a fork with some fixes (which are somewhat replicated on master of the json-bigint GH repo but not release)

We should use this for now:
https://www.npmjs.com/package/@cardanosolutions/json-bigint
