### ISSUE TITLE
Adapt NuFi wallet for E2E tests

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1279]
Please check if https://support.nu.fi/support/solutions/articles/80001042133-nufi-testnet-extension-installation is working with preview testnet. If not, mark this issue as blocked.

Otherwise,

- pack the extension and cut a new release in [e2e-assets repo](https://github.com/mlabs-haskell/ctl-e2e-assets/) (ask Amir how to do this if you are not Amir)
- Add code to control the wallet in the headless browser to the E2E test suite, similarly to how it is done for other wallets

Check-out from this branch: https://github.com/Plutonomicon/cardano-transaction-lib/pull/1265

**Comment by errfrom** [comment]
@klntsky @uhbif19 This extension only works with `preprod`, based on information I got from NuFi and my experience with it.

**Comment by uhbif19** [comment]
@errfrom Yes, I did not find a way to enable preview testnet support. We cannot test on preprod testnet?

**Comment by klntsky** [comment]
We can't.

@uhbif19 the test suite assumes a single network. Switching is not an option, we need to test `preview` features before they appear on `preprod` (that follows `mainnet` closely)

**Comment by klntsky** [comment]
We are not going to wait for E2E setup anymore, because the developers decided not to add a `preview` version.

Their response: https://discord.com/channels/884709419802308619/888429476558553138/1049302964130566204 (join NuFi server to read).

We will not delay including NuFi as a supported wallet anymore, but this issue should remain open & blocked, just in case NuFi team changes their mind.

**Comment by klntsky** [comment]
We will only add wallets to the e2e test suite if funded.
