### ISSUE TITLE
TOC in docs don't work anymore

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#1283]
We recently updated links in the TOC in docs to use what seemed to be the right query hash, but actually they don't work for me

e.g in https://github.com/Plutonomicon/cardano-transaction-lib/blob/bb4e1050f5dc19acdda6ff708bafe054ca5f1180/doc/ctl-as-dependency.md

The "Using CTL's overlays" section link doesn't work (#using-ctl-s-overlays), and clicking the anchor button next to the section title creates the link with the query hash #using-ctls-overlays

**Comment by klntsky** [comment]
Thank you. We need to find a TOC generator that follows github conventions for link generation.

**Comment by uhbif19** [comment]
@klntsky 

I found two solutions: doctoc and markdown-toc-gen. Both are installed with `npm`, generate the correct hashlink, and broke our `+` usage for sublists.

Both require usage of html comments to mark where TOC should be generated.

`markdown-toc-gen` has update and check modes. So we can add a check in the CI (add in `make check-format` I guess?).

`doctoc` seems to not have check mode, only update. Also, it adds some advertising link for itself, which could be removed first time and then do not appear again. It has Github action integration, but it looks like it creates separate PR with TOC generation - which does not look good solution to me. Also, we can do check manually with `diff`, or do not check at all - just add to `make format`.

**Comment by uhbif19** [comment]
@klntsky Looks like `markdown-toc-gen` breaks on code blocks marked with PureScript language. So we could not use it. `doctoc` have no such error.

I found no other options in npm except these two. So I think the only option is to use `doctoc`. For checking TOC formating I think I can copy .mds to a separate directory and diff with originals. Or just not check them.
