### ISSUE TITLE
testing framework

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-transaction-lib#13]
we need a testing framework that runs both on CLI and in simulated browser environments.

currently the plan is to pull in scaffolding from the Medea library https://github.com/juspay/medea-ps/blob/master/test/Main.purs
this uses `mote` and `spec` and `quickcheck` together nicely.   we may need a browser-specific test framework like Jest to give us everything to simulate browser behaviors.

**Comment by Benjmhart** [comment]
https://github.com/Plutonomicon/cardano-browser-tx/pull/16 - this brings in a CLI environment test suite for parsing, this can be extended to testing the websocket functions as well

we still need a simulated browser environment, (this will likely require some FFI)

**Comment by Benjmhart** [comment]
also no quickcheck yet.

**Comment by Benjmhart** [comment]
at this point we're not really using quickcheck,   we should probably build up json examples that fit a schema, the test library for medea-ps does that.  it might be a good place to start.

in short, the objective is to _exhaustively_ test all parsers.

this might include creating json that can break integer precision, please be advised.

**Comment by Benjmhart** [comment]
additional note - we might need such a generator for Data as well.

Data schemata don't have a spec language, can Medea do this?

**Comment by ngua** [comment]
I think our Plutip integration and e2e satisfy our most pressing testing needs now
