### ISSUE TITLE
Eternl wallet: respect UTxO locking

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1301]
Eternl UTxO locking feature (possibility for the user to prevent specific UTxOs from being spent by marking them as "locked" and thus hiding them from CIP-30 `getUtxos` output) is not compatible with our hack to make Eternl "see" the Utxos we are spending, namely, `waitForWalletInputs` function. See https://github.com/Plutonomicon/cardano-transaction-lib/issues/1282

We need to change our approach, specifically we should use Eternl (CIP-30) query layer as a source of truth.

In the balancer, whenever we query for utxos at own addresses, if the wallet is Eternl, we must use `getWalletUtxos` (CIP-30) instead of `utxosAt` (Kupo). Instead of waiting for Eternl to synchronize with our query layer, we must do the opposite: check that utxos that are seen by `utxosAt` are a superset of `getWalletUtxos` call output - it should be done on an earlier stage [(in the balancer)](https://github.com/Plutonomicon/cardano-transaction-lib/blob/2b6ea92809d72e93764f52acc42f1d1cdda444cb/src/Internal/BalanceTx/BalanceTx.purs#L161)

Note that we use `Constraints._srcAddresses` that may contain addresses not controlled by Eternl. So, we must first separate these addresses into those that are used by the wallet (CIP-30 `getUsedAddresses`) and those that are not. The latter group should be treated using our query layer (utxosAt) the same way as before.

**Comment by Luis-omega** [comment]
working on this, I found that my current approach for testing directly breaks the proposed solution. 

Basically, if the utxos are locked after the balance and before the transaction is signed we come back to the same problem. 

I think this could be triggered when there is a chain of utxos.

The good thing is that at least at the signature time we know that the problem could be a locked utxo.

**Comment by klntsky** [comment]
@Luis-omega 

> Basically, if the utxos are locked after the balance and before the transaction is signed we come back to the same problem.

We should ignore this, because no algorithm can save us from the problem of on-chain state changing between balancing and submission anyway. We should assume that the results of CIP-30 calls are not outdated at the moment of submitting a Tx.

> I think this could be triggered when there is a chain of utxos.

I don't think so, we lock utxos on our side in the balancer specifically to support chaining (for context: the word "lock" here refers to the locking mechanism in CTL itself)

**Comment by klntsky** [comment]
The approach that we followed to handle this has been significantly changed, see #1440.

Related discussion in Eternl discord:
https://discord.com/channels/907178289263681566/907569785611636757/1078720835352805457
