### ISSUE TITLE
Tx chaining doesn't work with Eternl after switching to Kupo for `getUtxoByOref`

### ISSUE THREAD

**Issue by errfrom** [Plutonomicon/cardano-transaction-lib#1311]
In order to make transaction chaining work with Eternl, we use a hacky solution in which we wait for `additionalUtxos` to be confirmed by the wallet before signing a transaction. 
https://github.com/Plutonomicon/cardano-transaction-lib/blob/a83dff3465f67c8d7b339bd5925a1440c5aab977/src/Internal/QueryM/Sign.purs#L56-L63

After switching to Kupo for utxos-related queries, `getUtxoByOref`, which is used by `walletWaitForInputs`, now fails to request utxos produced by yet unconfirmed transactions.

Solution: Update `walletWaitForInputs` to not request full utxos and just use output references to compare with entries returned by the wallet.

**Comment by klntsky** [comment]
Will be addressed by https://github.com/Plutonomicon/cardano-transaction-lib/issues/1301
