### ISSUE TITLE
CI does not run Hydra checks anymore

### ISSUE THREAD

**Issue by uhbif19** [Plutonomicon/cardano-transaction-lib#1313]
Looks like this commit in `develop` is last one for which Hydra was run (https://github.com/Plutonomicon/cardano-transaction-lib/commit/886e90fb6ab9233d73d793fb4b60fbba8d62491e). While I do not see anything related to CI change in newer commits.

**Comment by klntsky** [comment]
It's not our bug. We don't control the devops side of things.
