### ISSUE TITLE
Possible race condition in E2E tests with CI

### ISSUE THREAD

**Issue by errfrom** [Plutonomicon/cardano-transaction-lib#1335]
https://hercules-ci.com/accounts/github/Plutonomicon/derivations/%2Fnix%2Fstore%2F1q8f9wxlrb5rch0bnnac5kwn48w7ws0g-ctl-e2e-test.drv/log?via-job=80a8e054-b85e-4d08-b7b7-1c1ebd05ca9c

**Comment by klntsky** [comment]
It's because [here](https://github.com/Plutonomicon/cardano-transaction-lib/blob/7c11a8c39afd4902364439ae52b6f5457600c975/nix/default.nix#L360) we assume 3seconds is enough for a webserver to start. Probably it starts the browser before the webserver and the page fails to load
