### ISSUE TITLE
Can we drop some haskell related inputs for the flake

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#1341]
https://github.com/Plutonomicon/cardano-transaction-lib/blob/b7d4c891c5a58e1b0231723ff209d40f2c2253f6/flake.nix#L7-L10
(`iohk-nix`, `haskell-nix`, and `CHaP`)

I think they might have just been an oversight, we bind them to names in the outputs function but then don't use them.

**Comment by klntsky** [comment]
We need to just remove the lines and check if nix works (`make run-ci-actions` and `nix develop`)
