### ISSUE TITLE
Implement Blockfrost queries based on OpenAPI spec [Metatask]

### ISSUE THREAD

**Issue by errfrom** [Plutonomicon/cardano-transaction-lib#1365]
This issue lists all the Blockfrost queries that we need to implement, divided into logical blocks so that the work can be done by multiple developers in parallel. Feel free to assign yourself **(please put your username next to the task you are working on)**.

All work should be based on [#1260 Make Contract query backend configurable](https://github.com/Plutonomicon/cardano-transaction-lib/pull/1260).
***
### 1. Get utxos at address / by output reference (@errfrom https://github.com/Plutonomicon/cardano-transaction-lib/pull/1366)
- [x] `utxosAt` - https://docs.blockfrost.io/#tag/Cardano-Addresses/paths/~1addresses~1{address}~1utxos/get
- [x] `getUtxoByOref` - https://docs.blockfrost.io/#tag/Cardano-Transactions/paths/~1txs~1{hash}~1utxos/get
***
### 2. Get transaction metadata, Check transaction confirmation status (@jy14898 https://github.com/Plutonomicon/cardano-transaction-lib/pull/1368)
- [x] `getTxMetadata` - https://docs.blockfrost.io/#tag/Cardano-Transactions/paths/~1txs~1{hash}~1metadata/get
- [x] `isTxConfirmed` - https://docs.blockfrost.io/#tag/Cardano-Transactions/paths/~1txs~1{hash}/get
***
### 3. Submit / evaluate a transaction (@jy14898 https://github.com/Plutonomicon/cardano-transaction-lib/pull/1376)
- [x] `submitTx` - https://docs.blockfrost.io/#tag/Cardano-Transactions/paths/~1tx~1submit/post
- [x] `evaluateTx` - https://docs.blockfrost.io/#tag/Cardano-Utilities/paths/~1utils~1txs~1evaluate/post
***
### 4. Get datums / scripts by hash (@uhbif19 #1378)
- [x] `getDatumByHash` - https://docs.blockfrost.io/#tag/Cardano-Scripts/paths/~1scripts~1datum~1{datum_hash}~1cbor/get
- [x] `getScriptByHash`:
  - get `timelock` script by hash - https://docs.blockfrost.io/#tag/Cardano-Scripts/paths/~1scripts~1{script_hash}~1json/get
  - get `plutus` script by hash - https://docs.blockfrost.io/#tag/Cardano-Scripts/paths/~1scripts~1{script_hash}~1cbor/get
***
### 5. Get current epoch information (@Luis-omega https://github.com/Plutonomicon/cardano-transaction-lib/pull/1372)
- [x] `getProtocolParameters` - https://docs.blockfrost.io/#tag/Cardano-Epochs/paths/~1epochs~1latest~1parameters/get
- [x] `getCurrentEpoch` - https://docs.blockfrost.io/#tag/Cardano-Epochs/paths/~1epochs~1latest/get
***
### 6. Get blockchain information (@errfrom https://github.com/Plutonomicon/cardano-transaction-lib/pull/1377)
- [x] `getSystemStart` - https://docs.blockfrost.io/#tag/Cardano-Ledger/paths/~1genesis/get
- [x] `getEraSummaries` - https://docs.blockfrost.io/#tag/Cardano-Network/paths/~1network~1eras/get
- [x] `getChainTip` - https://docs.blockfrost.io/#tag/Cardano-Blocks/paths/~1blocks~1latest/get
***

**Comment by Luis-omega** [comment]
I would like to take `5. Get current epoch information`
