### ISSUE TITLE
Update `walletSpec` when `wallet` is changed

### ISSUE THREAD

**Issue by rynoV** [Plutonomicon/cardano-transaction-lib#1367]
When we change `QueryRuntime.wallet` we may also want to update `QueryConfig.walletSpec`. With `withKeyWallet` for example, the `walletSpec` may get out of sync with the `wallet`, which may cause issues for users who decide to use `walletSpec` instead of `wallet` for some reason.

In the `KeyWallet` case, we may not be able to reproduce the exact wallet spec as we don't know if key files were used, but we can at least use [these fields](https://github.com/Plutonomicon/cardano-transaction-lib//blob/c645c73ac2137ed3bdd67f155692d0fc8c13bfd1/src/Internal/Wallet/Key.purs#L78-L79)

**Comment by rynoV** [comment]
Alternatively, we might just remove `walletSpec` from the contract reader environment entirely

**Comment by jy14898** [comment]
I was thinking about this earlier, I'm not sure why we store the spec past contract setup

**Comment by klntsky** [comment]
This is not a bug. `WalletSpec` is simply a piece of input from the user, describing what they want from CTL initialization code.

We don't provide guarantees about it's relation to the Wallet (that is also user-replaceable)

It makes little sense to keep it after use, but removing it would require us to split QueryConfig in two parts, which would complicate the interface, so not worth it.

**Comment by jy14898** [comment]
Given the changes for blockfrost, I think it's now trivial to drop walletSpec from the env, as we use separate types for setup params vs the reader

**Comment by klntsky** [comment]
OK let's get back to it some time in the future
