### ISSUE TITLE
Key wallet support for testing

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#140]
The `Wallet` type should be extended with support for public and private keys

This should be integrated with a testing framework that has the following properties:

- Throws an exception if run in the browser
- If run in node, uses `fs` to write transactions generated during testing to disk
- The transactions should (probably?) be CBOR-encoded
- They can then be provided to Plutip

**Comment by Benjmhart** [comment]
this might use typhon or the `cardano-wallet` backend.
