### ISSUE TITLE
Expose or remove kupo defer-db-indexes

### ISSUE THREAD

**Issue by klarkc** [Plutonomicon/cardano-transaction-lib#1444]
https://github.com/Plutonomicon/cardano-transaction-lib/blob/30601b4431e1222e8002710ec1419056eb30990f/nix/runtime.nix#L126

I was struggling to identify the cause of the timeout issues with kupo requests. After talking with the kupo maintainer, I learned that the `--defer-db-indexes` option has little impact on performance for the preview network. He suggested disabling this option, and the initial indexing process takes around 20-30 minutes on the preview network. However, I found that there is currently no way to disable this option. Therefore, I recommend adding the option to the `buildCtlRuntime` function so that users can choose whether or not to use it based on their specific needs. Alternatively, it may be worth considering removing the option entirely, especially for recently created nodes where deferring the index would be meaningless.

**Comment by klntsky** [comment]
Please check out this: https://github.com/Plutonomicon/cardano-transaction-lib/pull/1448
