### ISSUE TITLE
typo: `ownPaymentPubKeyHashes`

### ISSUE THREAD

**Issue by MangoIV** [Plutonomicon/cardano-transaction-lib#1446]
- confusingly it's called `ownPaymentPubKeysHashes` instead of `ownPaymentPubKeyHashes`

**Comment by klntsky** [comment]
Thanks! Will fix soon

**Comment by klntsky** [comment]
OTOH, it's not grammatically incorrect. We are not refering to hashes of a single pubkey, but to hashes of multiple pubkeys. Pubkeys' hashes.

**Comment by MangoIV** [comment]
@klntsky theres at least two types with different names so perhaps the other type should be fixed to be pubkeyshashes, too

**Comment by klntsky** [comment]
@MangoIV `ownPaymentPubKeyHashes`  is not in the public API
