### ISSUE TITLE
Kupo retry mechanism tweaks

### ISSUE THREAD

**Issue by KristianBalaj** [Plutonomicon/cardano-transaction-lib#1452]
The following retry mechanism can be improved implemented in this commit: https://github.com/Plutonomicon/cardano-transaction-lib/commit/13adac22532a9bbedc7f52a11a975a6a53cdee21

It's just exponentially increasing the backoff time up to infinity. 
There should be a maximum backoff time specified (e.g. 32 seconds) + delay randomisation should be introduced, too.

**Comment by klntsky** [comment]
>  It's just exponentially increasing the backoff time up to infinity. 

That's exactly how it should work. Only then we can guarantee that you will not self-DOS the server and if it has a fixed and non-zero capacity, _eventually_ it will serve everyone.

> delay randomisation should be introduced, too.

No need to, because the clients are not going to hit the server at the same time.
