### ISSUE TITLE
Remove typed validators

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1463]
- They are not widely used
- They force boilerplate on those who don't use them
- They don't play nicely with our domain, because they limit us to interact with only one script per tx

Related: #843

**Comment by klarkc** [comment]
I've spent a lot of time trying to figure out why we have typed validators. If typed validators aren't necessary, then I think we should get rid of them.

> They don't play nicely with our domain, because they limit us to interact with only one script per tx

I'm not sure why that would be the case. Can't we just add more typed validators as lookups using ScriptLookups?

What are we gaining from typed validators in CTL?
