### ISSUE TITLE
Switch from `Data.BigInt` to `JS.BigInt`

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#1472]
- https://github.com/purescript-contrib/purescript-bigints that uses `big-integer` NPM package is deprecated
- https://github.com/purescript-contrib/purescript-js-bigints uses native bigints

**Comment by kozross** [comment]
I don't think this is possible without a compiler upgrade. Even on 1.2.0 (which is [a year old](https://github.com/purescript-contrib/purescript-js-bigints/commit/a23c0ec1b3cb6c8468202221f51b162c2aa81516)), I get the following:

```
[1/3 ModuleNotFound] .spago/js-bigints/a23c0ec1b3cb6c8468202221f51b162c2aa81516/src/Js/BigInt/BigInt.purs:23:1

  23  import Data.Reflectable (class Reflectable, reflectType)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Module Data.Reflectable was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```

This is a module that was introduced in a more recent version of Purescript than the one we run.

**Comment by klntsky** [comment]
Sorry @kozross,  forgot to mention it should be done on top of https://github.com/Plutonomicon/cardano-transaction-lib/pull/1521
