### ISSUE TITLE
`scriptCurrencySymbol` doesn't need to return `Maybe`

### ISSUE THREAD

**Issue by zmrocze** [Plutonomicon/cardano-transaction-lib#1491]
THIS IS A DETAIL

Function
```
scriptCurrencySymbol :: MintingPolicy -> Maybe CurrencySymbol
scriptCurrencySymbol = mpsSymbol <<< mintingPolicyHash
```
from [here](https://github.com/Plutonomicon/cardano-transaction-lib/blob/10a88faa2e6237aafc90568e3488f3421517af63/src/Internal/Scripts.purs#L101)
seemingly doesn't need to have `Maybe` type.

`Maybe` there stems from `mpsSymbol` checking if provided ByteArray is empty or correctly decodes as hash. We know that it's a hash, so 
```
scriptCurrencySymbol :: MintingPolicy -> CurrencySymbol
scriptCurrencySymbol = CurrencySymbol <<< mintingPolicyHash
```
has the same semantic as long as results of `mintingPolicyHash` correctly decode with `scriptHashFromBytes` (which they should).

**Comment by zmrocze** [comment]
Ok, I see why its so - you don't export `CurrencySymbol` constructor

**Comment by klntsky** [comment]
I agree, would you like to make a PR to change it? We can export the constructor in internal module - just not in `Contract.*`.

**Comment by zmrocze** [comment]
yup, was stopped at the export, will submit sth tomorrow
