### ISSUE TITLE
awaitTxConfirmed is flaky with kupo

### ISSUE THREAD

**Issue by nrutledge** [Plutonomicon/cardano-transaction-lib#1501]
## Problem

`awaitTxConfirmed` seems to repeatedly query kupo for the presence of the transaction that was submitted. If at any point kupo returns an error response (e.g., if it is overloaded momentarily), `awaitTxConfirmed` will error out.

## Proposed Solution

It would be ideal if there was retry behavior to make this more robust.  For one project, @Geometer1729 created the following for this purpose:
```purescript
import Contract.Transaction (awaitTxConfirmed)
import Control.Monad.Error.Class (class MonadError)
import Data.Time.Duration (Seconds(..))
import Effect.Aff (Error)
import Effect.Aff.Class (class MonadAff)
import Effect.Aff.Retry (constantDelay, limitRetriesByCumulativeDelay, recovering)

awaitTxConfirmed' :: TransactionHash -> Contract Unit
awaitTxConfirmed' = simpleRetry <<< awaitTxConfirmed

simpleRetry :: forall m a. MonadAff m => MonadError Error m => m a -> m a
simpleRetry = recovering policy [ (\_ _ -> pure true) ] <<< const
  where
  policy =
    limitRetriesByCumulativeDelay (Seconds 30.0)
      $ constantDelay (Seconds 1.0)
```

This is just a quick fix. The ideal solution likely involves adding the retry behavior at a lower level that gives retry behavior to all kupo queries.

**Comment by klntsky** [comment]
Retry functionality has been added here for Kupo https://github.com/Plutonomicon/cardano-transaction-lib/pull/1436 - only 503 error leads to another attempt.

**Comment by nrutledge** [comment]
@klntsky In our case, we have kupo behind nginx proxy which returns `502` when kupo is overloaded. We can look into adjusting that, but I'm wondering if it is worth retrying on more than just `503` specifically?
