### ISSUE TITLE
Better documentation for `BigNum`

### ISSUE THREAD

**Issue by kozross** [Plutonomicon/cardano-transaction-lib#1550]
It isn't currently specified anywhere what `BigNum` actually is: a 64-bit integer. We should document this information (and by extension, why this forces some conversions to be partial).

**Comment by klntsky** [comment]
https://github.com/mlabs-haskell/purescript-cardano-types/blob/715d4b2dcf8b29cb45001209ee562f758a513261/src/Cardano/Types/BigNum.purs#L68
