### ISSUE TITLE
eraSummaries decoding error

### ISSUE THREAD

**Issue by sadMaxim** [Plutonomicon/cardano-transaction-lib#1564]
I use last commit #1532 from develop branch.  And I am getting error in eraSummaries:

```bash
Error: Failed to parse the result: An error occurred while decoding a JSON value:
  At object key 'start':
  At object key 'time':
  Expected value of type 'Number'.
```
I guess it is an issue with new Ogmios 6.0 format. Now `"time":{"seconds":0} ` is an object , not a Number.

I tried it with docker image `cardanosolutions/ogmios:v6.0.0-rc4` , but everything ok with `ctl-runtime-ogmios`

**Comment by klarkc** [comment]
I've solved this in #1593
