### ISSUE TITLE
Switch to Ogmios for ex unit calculation

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-transaction-lib#174]
- This arises from https://github.com/Plutonomicon/cardano-browser-tx/issues/167 where we intend to add a buffer for executions units of redeemers as a temporary solution.
- To improve on this, we can call Ogmios to add the ex units on a transaction with the redeemers added. The ordered redeemers are contained in the field `redeemers` `ConstraintProcessingState`
- See https://ogmios.dev/mini-protocols/local-tx-submission/#evaluatetx

**Comment by ngua** [comment]
Since we are going to take care of #273 for stage 4.1, we can avoid deserialization entirely, so this issue is blocked until that's complete

**Comment by ngua** [comment]
Moving this back to 4.1

**Comment by errfrom** [comment]
@klntsky Yes, I think we can close it
