### ISSUE TITLE
More tight coupling between `UsedTxOutRefs` cache and a wallet in `QueryConfig`

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-transaction-lib#179]
The cache helps represent the actual state of utxos available for a particular wallet. Therefore the abstraction using both should be organized to make it clear and convenient.

**Comment by adamczykm** [comment]
Ideas?

**Comment by klntsky** [comment]
Not needed. We should not intercept wallet calls and modify the returned values in CIP-30 methods we expose to the user (that would be a horrible/confusing thing to do). `UsedTxOutRefs` is an internal thing and it serves it's purpose just right when not being exposed.
