### ISSUE TITLE
`applyCode` implementation

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#189]
The partially and fully applied scripts obtained from the `apply-args` endpoint don't match the CBOR hex provided by @t4ccer. The endpoint does produce valid scripts, however, in that they serialize and deserialize correctly. Possible reasons:
- `applyArguments` produces different results than `fromCompiledCode . applyCode` 
- different Plutus versions?

**Comment by ssorc3** [comment]
`applyArguments` does produce different results from `fromCompiledCode . applyCode` as can been seen below with a basic validator that always succeeds:
```
> applyArguments testScript [I 1]
"530100003332222220061200120014c101010001"
> testScriptWithArgs 1
"5001000033322222200612001200148009"
```
The reason for this is that `applyArguments` uses `[Data]` for the list of arguments but `applyCode` uses a `Lift` instance to generate the PLC code.
For example for an `Integer` we generate these:
```
> getPlc (liftCode (BuiltinData (I 1)) :: CompiledCodeIn DefaultUni DefaultFun BuiltinData)
Program () (Version () 1 0 0) (Constant () (Some (ValueOf data (I 1))))
> getPlc (liftCode 1 :: CompiledCodeIn DefaultUni DefaultFun Integer)
Program () (Version () 1 0 0) (Constant () (Some (ValueOf integer 1)))
```

If we can generate the PLC from the `Lift` instance then we can use `applyProgram` to apply it to the partial validator and I think it should be the same as using `applyCode`.

**Comment by ngua** [comment]
Nice work @ssorc3! If we could keep using `applyArguments`, that would be ideal

**Comment by ssorc3** [comment]
I don't think we can easily change `applyArguments` because it's used internally by `applyValidator` for example. The only way we can keep using `applyArguments` is to wrap scripts so that they take `Data` or `BuiltinData` instead of Haskell types. 

Alternatively we can use the code I wrote above, which is similar to `applyArguments` but doesn't take `[Data]`. Or maybe it could unwrap the data before applying it but I think that would limit the types you can use as arguments to `Integer` and `ByteString`.

**Comment by ngua** [comment]
> Alternatively we can use the code I wrote above, which is similar to `applyArguments`

I think this is the better choice

The real issue here would be making sure we could obtain the PLC corresponding to a given `Lift` instance, no? It seems that this would unfortunately entail either
- building the PLC on the client from a given type (which would be absurdly complex I think)
- limiting the types that can be used as script parameters as you point out

**Comment by L-as** [comment]
FWIW `applyCode` isn't the most general form, and isn't the most efficient form either. If you look to support the most efficient scripts, you should support applying arbitrary `Term` to `Term`. You can do this by simply using the constructor.
