### ISSUE TITLE
Error Recovery Mode

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-transaction-lib#233]
currently, if a websocket dies, we just clear all listener sets and throw an error.

we should build a specific output (such as the pending queries in a queue to be resent, transactions that may have been submitted) for the error state, and a function which can accept this output, along with new websockets,  and restart those same queries, verify transactions were submitted/settled, etc.

**Comment by nrutledge** [comment]
An example of the problem with error handling is the `callMarketPlaceListNft` function here: https://github.com/Plutonomicon/cardano-transaction-lib/blob/seabug-deployment/npm-packages/cardano-transaction-lib-seabug/index.js

If the websocket fails to connect when fetching the list of NFTs, the operation is aborted but the promise remains in a pending state. This means the JS logic has no way of handling the failure.

In addition to the retry behavior mentioned in the description, it's also important that promises are properly rejected in the case of complete failure (or a certain number of retries have failed). Alternatively, there could be more of a pub/sub approach (e.g., event listeners/callbacks) so status updates can be communicated along the way to JS land.
