### ISSUE TITLE
Create `RawBytes` and `CborBytes` as newtypes over `ByteArray`

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-transaction-lib#234]
- Due to the different representations we have to deal with, we should newtype `ByteArray` so we can write valid `DecodeJson` instances for example.

**Comment by adamczykm** [comment]
Since they'll be wrapping Bytearray why the Hex suffix?

**Comment by ngua** [comment]
I was going to take care of this but I haven't had the time recently. I think this would be a good issue for a new contributor to take care of
