### ISSUE TITLE
MakeIsDataIndexed implementation?

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-transaction-lib#25]
we're going to need to encode and decode data in a reasonable way. - and to make sure that data instances agree  from Haskell -> Purescript.

This might be a place where we can employ Purescript-bridge, which allows you to construct json-compatible purescript types from haskell types.

the package itself is poorly maintained, and implies that there's a strategy pattern of sorts for building custom instances, etc.   This does not actually exist and everyone forks it.

here is a good fork i think: https://github.com/input-output-hk/purescript-bridge/

**Comment by Benjmhart** [comment]
adding to this, we can probably use the json serializer here since data is a subset of json, however it's going to be important that we get this behaving predictably and correctly.

**Comment by ngua** [comment]
Will be partially addressed in #209

**Comment by ngua** [comment]
Ah, didn't mean to close this, since we still need #59

**Comment by ngua** [comment]
Ah, didn't mean to close this, since we still need #59
