### ISSUE TITLE
Keep a CHANGELOG

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-transaction-lib#283]
I personally find changelogs very useful and prefer projects that keep them. It may be a non-urgent issue but I think we should all refresh https://keepachangelog.com/en/1.0.0/ and start keeping our own.

**Comment by Benjmhart** [comment]
this should begin with the stage 5 release (v2)

**Comment by klntsky** [comment]
Changelog makes sense only when we have a stable public API as well as versioning.
