### ISSUE TITLE
Add `getTxById` to `Contract` interface

### ISSUE THREAD

**Issue by Benjmhart** [Plutonomicon/cardano-transaction-lib#30]
these are currently blocked on Ogmios-datum-cache efforts

however we will need to be able to query tx by txid and datum by datumhash. (ideally against a cache layer.

**Comment by ngua** [comment]
We should be able to tackle this soon since `ogmios-datum-cache` is done, with a websocket interface too

**Comment by ngua** [comment]
We already have #113 for datums so we can make this one more specific as well

**Comment by ngua** [comment]
Currently blocked on https://github.com/mlabs-haskell/ogmios-datum-cache/issues/35. Moving it up to stage 4.1 nonetheless since this will simplify things for a lot of adopters
