### ISSUE TITLE
Add FAQs, scaffolding story to docs/wiki

### ISSUE THREAD

**Issue by peter-mlabs** [Plutonomicon/cardano-transaction-lib#302]
A project I'm working on will be scaffolding a CTL project soon, and I have some general questions that aren't quite covered by the README:

- If a new project wants to use CTL, is the preferred way to begin this by basing off of this repo? Or is CTL a library that's included (similar to the setup with plutarch) as a component of an otherwise standard project setup?
- Are the infrastructure components meant to be run locally or in the cloud? (Slack messaages are leading me to believe it's the latter)
  - Are there any knowledge pre-requisites to using CTL in terms of infra? Do developers need to be familiar with SQL, how to interact with the cardano-node/ogmios? If so, how familiar?
- Are there any deployment utilities ready? Are any officially supported? If so, which? Where can they be found? (@bladyjoker says he has a docker image ready, pending client sign off; Tomasz is working on an arion based solution)
- Where can general docs be found? It's not clear where/if the API is documented.
- Are there any open-source projects that can be looked as an example? I believe seabug does/will fit this bill. Let's throw a link in the README.

Mostly recording these questions here so I have a place to publicly centralize answers as they arise. Some of these questions are in the process of being answered in discord or slack, and I'll update this issue as the answers are found.

**Comment by klntsky** [comment]
Done.

**Comment by peter-mlabs** [comment]
Many thanks for your work here!
