### ISSUE TITLE
Thoroughly document public API

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#318]
Go through the entire public API and make sure everything is thoroughly documented

**Comment by jy14898** [comment]
@ngua  I wouldn't say #382 is a duplicate of this issue, I think this meta-issue just needs renaming. As it is, #381 isn't enough to close this issue (I hadn't planned on going through the public API to ensure documentation in that PR)

**Comment by ngua** [comment]
OK, we can rename this, I forgot about the extra documentation aspect

**Comment by ngua** [comment]
I'd say our documentation suffices now for v1
