### ISSUE TITLE
Keep WebSockets alive and reuse them between Contract calls.

### ISSUE THREAD

**Issue by adamczykm** [Plutonomicon/cardano-transaction-lib#320]
> some things about the existing API and it's usage in seabug:
> 
> it looks like for each transaction we're bootstrapping new websockets, the api should be such that we kind of keep websockets alive and pass them into the new readerT when we run a new CTL function.

**Comment by klntsky** [comment]
Isn't it possible to keep the entire application in `Contract`? We can `liftAff` so technically it's possible.

**Comment by klntsky** [comment]
Also, I think it's possible to reuse the websockets, since they are stored in `ContractConfig`:

```
  cfg <- defaultContractConfig
  runContract_ cfg foo
  runContract_ cfg bar
  ...
```
