### ISSUE TITLE
Add tests for tx deserialization

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#355]
Tests were not a part of #335, so we should add some. This could also be a part of #174

**Comment by ngua** [comment]
Moving to stage 5 since that's when we'll need this (see #174)

**Comment by ngua** [comment]
Marking this as "invalid" since we might not even need tx deserialization. Waiting for #273 to confirm

**Comment by klntsky** [comment]
Done long ago, including roundtrip tests
