### ISSUE TITLE
Calculate ex units on server

### ISSUE THREAD

**Issue by bladyjoker** [Plutonomicon/cardano-transaction-lib#360]
To successfully run Plutus Scripts we need correct execution units (xu) budget calculations to be performed.

Options that we've scoped out so far that will get us there asap are:
1. Ogmios [evaluateTx](https://ogmios.dev/api/modules/_cardano_ogmios_client.TxSubmission.html) method
2. mlabs-haskell/bot-plutus-interface implementation (using cardano-node lib)

It would be good to know how the 2 methods compare in terms of xus calculated.

**Comment by ngua** [comment]
Related: #174

**Comment by ngua** [comment]
For reference, the BPI approach: https://github.com/mlabs-haskell/bot-plutus-interface/blob/91b18e1d73227d21a99007cb1568341dfa6c3391/src/BotPlutusInterface/CardanoCLI.hs#L514

**Comment by ngua** [comment]
We'll go with the server now, it will be faster and less error-prone to implement

**Comment by ngua** [comment]
Since the tx deserialization code is untested (and bugs are fairly likely given our past experiences with CSL integration), I'm going to use the server to take care of this. I'm planning on extending `finalizeTx` to take care of it
