### ISSUE TITLE
Mobile bindings

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#362]
There's interest for getting CTL to work on mobile. There are different approaches to solving this:

- Use React native (see https://github.com/doolse/purescript-reactnative). Although this is primarily a UI lib and would require rethinking some CTL internals
- Connect to dApps via the integrated webview

We'll also need to make our wallet integration a bit more sophisticated. At the moment, we just look for `window.cardano.*`, but this is browser-specific

**Comment by klntsky** [comment]
Looks like the way to go is the second option. We have already presented a Lode webview-based demo with very little effort, proving viability of CTL on mobile UX.

**Comment by uhbif19** [comment]
@klntsky I do not understand what the task is for the second option. Like CIP-30 works the same in this case?
