### ISSUE TITLE
Use ogmios-datum-cache reflection in our code

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#363]
Currently, to match ODC responses to requests we don't use reflection that is implemented in https://github.com/mlabs-haskell/ogmios-datum-cache/pull/13 because it was not available earlier.

We need to address that.

This may make it possible to unify some code for ogmios and ogmios-datum-cache requests.

**Comment by ngua** [comment]
It's been merged: https://github.com/mlabs-haskell/ogmios-datum-cache/pull/31
