### ISSUE TITLE
Add additional `EncodeJson` instances

### ISSUE THREAD

**Issue by peter-mlabs** [Plutonomicon/cardano-transaction-lib#369]
`CurrencySymbol` has a [`DecodeJson` instance](https://github.com/Plutonomicon/cardano-transaction-lib/blob/cb0af8f023a7f5f1cadeba8a8f2e02523f661371/src/Cardano/Types/Value.purs#L190-L197), but no `EncodeJson`. This means that types that are exported via the `argonaut` option to purescript-bridge fail when they wrap a currency symbol.

**Comment by ngua** [comment]
We can also add one for `Rational`. Let me know if there's more types that need the instance
