### ISSUE TITLE
Construct exact POSIXTimeRange given to TxInfo

### ISSUE THREAD

**Issue by t1lde** [Plutonomicon/cardano-transaction-lib#410]
There are cases where we need to be able to obtain the *exact* POSIXTimeRange that gets passed to scripts with TxInfo - for example if the there are time-dependent values on Datums.

The problem is that there is a round-trip conversion from 

- the POSIXTimeRange provided to `MustValidateIn`
- Conversion to `Slot`
- conversion to `TransactionValiditySlot`
- conversion *back* to POSIXTimeRange, when the ledger constructs TxInfo

See pg 35 of the [Alonzo spec](https://hydra.iohk.io/job/Cardano/cardano-ledger/specs.alonzo-ledger/latest/download-by-type/doc-pdf/alonzo-changes) for part of the conversion. This may also require some reverse-engineering of the cardano-ledger

**Comment by Saizan** [comment]
I did some digging and `cardano-ledger` implements `slotToPOSIXTime` [1], using `epochInfoSlotToUTCTime`
https://github.com/input-output-hk/cardano-ledger/blob/2acff66e84d63a81de904e1c0de70208ff1819ea/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L186-L203

That function in turn is provided by `cardano-slotting`, with addtional parameters about the protocol and epoch:
https://github.com/input-output-hk/cardano-base/blob/8fe904d629194b1fbaaf2d0a4e0ccd17052e9103/slotting/src/Cardano/Slotting/EpochInfo/API.hs#L80-L85

Most things can be directly queried from the node, and the `EpochInfo` can be calculated from `EraHistory` which can also be calculated.
https://github.com/input-output-hk/cardano-node/blob/91a11ba26707d2de1c72abfe4a15f59f84e8e349/cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs#L1313-L1316

**Comment by Saizan** [comment]
Ultimately it comes down to properly using the outputs of the following `slotToWallclock` query. In that module we also have `wallclockToSlot` which would be useful in the other direction.

https://github.com/input-output-hk/ouroboros-network/blob/bd9e5653647c3489567e02789b0ec5b75c726db2/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/History/Qry.hs#L461-L481
