### ISSUE TITLE
Simplify fundeps in From/ToPlutusType

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#411]
https://github.com/Plutonomicon/cardano-transaction-lib/blob/fb2ae073af1f61b928ab2a3f290954851e5080fd/src/Plutus/ToPlutusType.purs#L41-L43

Should be able to be turned into

```haskell
class ToPlutusType f t pt | t -> pt f where
  ...
```

As `pt` is already determined by `t`

I'd argue we don't even need `f`, which removing would simplify the `Identity` cases

**Comment by klntsky** [comment]
Closing in favor of https://github.com/Plutonomicon/cardano-transaction-lib/issues/452
