### ISSUE TITLE
Better APIs for modifying finalized/balanced Transaction structure

### ISSUE THREAD

**Issue by t1lde** [Plutonomicon/cardano-transaction-lib#414]
Currently, it is a bit of a headache to deal with transaction structures manually, within the pipeline of Contract actions required to construct valid transactions.

## Use-Case

Our use-case is that a specific ordering of transaction outputs is required for a particular transaction type, as a plutus-optimisation.

## Suggestion 

Currently this is a little awkward - the construct, balance, reindex, finalize, sign pipeline makes this annoying (currently signing the transaction, modifying & re-signing it to not have to decompose `balanceAndSignTx`).

Having the component parts of `balanceAndSignTx` compose better would improve this situation

**Comment by klntsky** [comment]
Unbalanced transaction can be modified manually before balancing. We can't make the APIs for modifying a balanced transaction better, because a balanced transaction is a transaction with certain properties that can be accidentally broken.
