### ISSUE TITLE
[Metatask] Plutip integration

### ISSUE THREAD

**Issue by t1lde** [Plutonomicon/cardano-transaction-lib#426]
What's the situation here? iirc there was something blocking private testnet usage. Is that right? 

- Do private testnets work currently?
- How can it be setup? (is it just setting the protocol params & testnet magic no correctly)

See also: [plutip integration](https://github.com/mlabs-haskell/plutip/issues/59)

**Comment by klntsky** [comment]
I am going to try setting up private testnet and using it with CTL. Will report here and in the channel.

**Comment by klntsky** [comment]
Context update: I'm working on a new plutip-server binary exposing HTTP endpoint that will allow:

- starting local cluster
- sending transactions
- stopping local cluster

**Comment by marijanp** [comment]
> Context update: I'm working on a new plutip-server binary exposing HTTP endpoint that will allow:
> 
>     * starting local cluster
> 
>     * ~sending transactions~ UPD: we will submit through ogmios
> 
>     * stopping local cluster

@klntsky I'm also interested in integrating `plutip`. What has your research/ work shown so far, what do you think are the necessary changes to `plutip` and to `ctl` to make things work?

My proposal looks like this:
 - `plutip`: 
   - make it return data (socket the node listens on, wallet pkh, wallet address) in a more structured way e.g. `json`
   - add more return data: we will need a signing key for the generated value to be able to send funds in a testing scenario
   - we will probably also need a way to generate new wallets for more interesting test-cases
 - `ctl`
   - modify `buildCtlRuntime` and `launchCtlRuntime` such that we we replace the `cardano-node` container with the local cluster through an configuration option and additionally make sure that the other instances like `ogmios` are configured properly.

I would be happy to help you with this issue.

**Comment by klntsky** [comment]
> plutip: make it return data (socket the node listens on, wallet pkh, wallet address) in a more structured way e.g. json

This has already been done in my stash, expect a PR soon.

> add more return data: we will need a signing key for the generated value to be able to send funds in a testing scenario

Yep, I've done that already in my prototype.

> we will probably also need a way to generate new wallets for more interesting test-cases

What do you mean by generate? We can pre-allocate enough funds and move them as we wish on the client, so that's up to the client-side (CTL).

> modify buildCtlRuntime and launchCtlRuntime such that we we replace the cardano-node container with the local cluster through an configuration option and additionally make sure that the other instances like ogmios are configured properly.

I decided to go the other route. [I made another monadic wrapper over `Contract`](https://github.com/Plutonomicon/cardano-transaction-lib/pull/470/files#diff-230fb24d0be65335bfd35ee9f246fb2b1a205c7cb09a95eb0eda2a12655fd24aR69) that is interpreted into `Aff` (cluster startup is it's effect). The interpreter provides correct configs for the inner `Contract` runner.

**Comment by marijanp** [comment]
> What do you mean by generate? We can pre-allocate enough funds and move them as we wish on the client, so that's up to the client-side (CTL).

True, one wallet is enough.

> I decided to go the other route. [I made another monadic wrapper over Contract](https://github.com/Plutonomicon/cardano-transaction-lib/pull/470/files#diff-230fb24d0be65335bfd35ee9f246fb2b1a205c7cb09a95eb0eda2a12655fd24aR69) that is interpreted into Aff (cluster startup is it's effect). The interpreter provides correct configs for the inner Contract runner. The reason why we need another wrapper is because we want to separate CTL+plutip use scenario from CTL-only use, because of the need to bundle for the browser.

Great, this would have been my follow-up proposal. The thing I suggested was rather a quick solution to somehow obtain a local "runtime".

Thanks for your efforts, this sounds promising.

**Comment by peter-mlabs** [comment]
Very happy to see this merged @klntsky! Great work!
