### ISSUE TITLE
Implement E2E in-browser tests for wallets

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#465]
Here's an instruction to test extensions with puppeteer that looks very convincing:

https://www.gokatz.me/blog/automate-chrome-extension-testing/

- Investigate how can we apply it to Nami and Gero right away (they should have stable extension IDs)
- Investigate how can we preserve extensions data (wallets and wallet passwords) between test runs

What we need to consider:

- Assuming we are going to have wallets stored in a public repo, someone might steal our testnet ada (not terrible, but annoying)
- waiting for testnet tx confirmations might take a lot of time

**Comment by ngua** [comment]
We can use https://github.com/justinwoo/purescript-toppokki for this. We might need to write a bit of FFI stuff but it shouldn't be too bad (I'm guessing extensions aren't support atm)
