### ISSUE TITLE
QuickCheck support

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#466]
It may be a good idea to add `Arbitrary` instances to all of our types (in PureScript orphans are disallowed, which makes testing a bit harder because of the need to define newtypes).

**Comment by Luis-omega** [comment]
This seems like something that I could help with and something that would help me either. So unless stated otherwise I will work on it. 

I probably would need some help to spot some corner cases but it could be done as part of the review process.

**Comment by klntsky** [comment]
I doubt our clients are testing their Contract-related code in ways that would let them benefit from arbitrary value generation. Usually, the tests involve running async code and can't be implemented as unit tests or property tests. We should close this until we see anyone actually interested in Arbitrary instances.
