### ISSUE TITLE
Make nix builds faster

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#478]
Currently we rebuild the whole PS set when bundling with nix.

I think we can build purescript dependencies in a separate derivation and simply copy the `output/` dir from there.

**Comment by ngua** [comment]
`purs` apparently can't do this, so we have two options:
- compile everything once (and remove `srcs` argument to filter/select the project sources)
- keep the current setup

**Comment by ngua** [comment]
This was closed by a previous PR
