### ISSUE TITLE
Add One Shot Minting

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-transaction-lib#480]
There has been request for a [one shot minting contract](https://playground.plutus.iohkdev.io/doc/haddock/plutus-use-cases/html/Plutus-Contracts-Currency.html#v:mintContract).

We can replicate this by writing a Plutarch script that replicates the minting policy as above, parametrised by `TxOutRef/TransactionInput`, this (unapplied) script will then be serialised using `Codec.Serialise (serialise)` or `encode $ toJSON script` for `script :: Script` (in Haskell) and `import Data.Aeson (encode, toJSON)`. I would suggest the former as the latter is deprecated for newer revs. On CTL side, we should call `applyArgs` to any utxo from the user's utxo set.

This would provide an almost e2e public example for serialising and creating a contract (we can complete it by invoking the browser if we wish).

The Plutarch code should be public and open to optimisations:
1) Inside CTL by adding in an **optional** Nix Plutarch dep, with serialisation functionality added.
2) In a separate repo containing other Plutarch examples with corresponding serialised scripts e.g. always validate, always mints etc. We can then call in serialised one shot minting script to CTL.

First option isn't really ideal as we'd have to carry Plutarch as a dep.

**Comment by klntsky** [comment]
See https://github.com/Plutonomicon/cardano-transaction-lib/pull/848

**Comment by uhbif19** [comment]
@klntsky Looks like this is solved by PR, no?

**Comment by klntsky** [comment]
Yep, thanks @uhbif19
