### ISSUE TITLE
Replicate UPLC API on frontend

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#483]
We should be able to deprecate the current implementation of `applyArgs` by just recreating Plutus' UPLC in Purescript

**Comment by klntsky** [comment]
There's a wasm implementation of `applyArgs`: https://github.com/txpipe/aiken/blob/d11b8858bab6b334df3bf4976cb5e31018db6217/crates/uplc/src/tx.rs#L138 (uplc package on [crates.io](http://crates.io/))
It's used in CML, and Lucid uses it [like this](https://github.com/spacebudz/lucid/commit/ddb0165dc7ff1b55af12e93867bca7ae90251a38)
