### ISSUE TITLE
Fee calculation for minting an NFT and sending to a script address (for a specific wallet)

### ISSUE THREAD

**Issue by vvtran** [Plutonomicon/cardano-transaction-lib#491]
I have a situation where I am minting an NFT and sending to a script address, but getting fee calculation issues
```
fromList [("err",Object (fromList [("fee",Number 234490.0),("kind",String "FeeTooSmallUTxO"),("minimum",Number 234666.0)])),("tx",Object (fromList [("txid",String "d7e02c59")])),("kind",String "TraceMempoolRejectedTx"),("mempoolSize",Object (fromList [("bytes",Number 0.0),("numTxs",Number 0.0)]))]
ogmios_1              | {"severity":"Info","timestamp":"2022-06-03T10:21:10.181262067Z","thread":"1276","message":{"WebSocket":{"contents":{"agency":"ServerAgency TokBusy","tag":"RejectTx","event":"receive","reasons":[{"feeTooSmall":{"requiredFee":234666,"actualFee":234490}}]},"tag":"WebSocketClient"}},"version":"v5.2.0"}
```

**Comment by vvtran** [comment]
It turns out this was an issue for my specific wallet,  `addr_test1qpkl55y6av6lvu9gfjkqr0cmtkxn7qcezgg0q3vr0m2huda6qh8x3elu6qa9t48ymn0dluh805ws2we38uxwxcnzyygq5jl946`
I created a new wallet `addr_test1qp7l9wfw40l8ac2at0g9mtc32uhnljhrkupxs5dttkwj3eswrtzmr8ql4rc58d89s5lckr5rkx6m9dv75fu464wfguaqmaceek` and the transaction went through. My first wallet has a pretty niche selection of value/utxos, I wonder if this is a min. Ada issue.

**Comment by ngua** [comment]
Since we don't know what's causing this we can remove it from stage 4 and include a possible fix in a future patch release
