### ISSUE TITLE
Helper for loading private keys

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#523]
As part of https://github.com/Plutonomicon/cardano-transaction-lib/pull/437, `PrivateKey`s can now be used to create a `Wallet`. To enable easier use of such wallet, we could provide helpers to extract the private key from the signing-key file exported from cardano-cli. Eg
parse
```
{
    "type": "PaymentSigningKeyShelley_ed25519",
    "description": "Payment Signing Key",
    "cborHex": "582085f8d4382c92c17efcef0f20f9397abcedcd5fd9e576a6dcc99e582eb275b79d"
}
```
into `85f8d4382c92c17efcef0f20f9397abcedcd5fd9e576a6dcc99e582eb275b79d`, loaded into the `CSL` `PrivateKey` type

**Comment by ngua** [comment]
This would be a great addition

**Comment by klntsky** [comment]
This instruction should be updated when the loader is implemented:
https://github.com/Plutonomicon/cardano-transaction-lib/pull/437/files#diff-fec82e327e0c484b9d125432afa96364f8188be4df1d7e3b102778095d347020R185
