### ISSUE TITLE
Blockfrost exploration

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#524]
Here's how blockfrost API endpoints map to our needs:

# ctl-server

`apply-args` - not supported, [we will implement it eventually on frontend](https://github.com/Plutonomicon/cardano-transaction-lib/issues/483)

# ogmios
- `utxo` - `/addresses/:address/utxos`
- `getProtocolParameters` - `/epochs/:number/parameters`
- `systemStart` - `/genesis`
- `currentEpoch` - `/epochs/latest`

Example response:

```json
{
    "epoch": 210,
    "start_time": 1654719616,
    "end_time": 1655151616,
    "first_block_time": 1654719619,
    "last_block_time": 1654786336,
    "block_count": 2002,
    "tx_count": 8121,
    "output": "56485150782946429",
    "fees": "2913192162",
    "active_stake": "15044495200974246"
}
```

- `eraSummaries` - supported

Looks like we can get era summaries via blockfrost  https://docs.blockfrost.io/#tag/Cardano-Network/paths/~1network~1eras/get

https://github.com/blockfrost/blockfrost-backend-ryo/issues/15

- `chainTip` - `/blocks/latest`

Example response:

```json
{
    "time": 1654785927,
    "height": 3617406,
    "hash": "247b93ef3bbcdfeabdc8fd0ea1bae21d636f56246ebce0b9364e0f22fdda0e77",
    "slot": 60416711,
    "epoch": 210,
    "epoch_slot": 66311,
    "slot_leader": "pool18yslg3q320jex6gsmetukxvzm7a20qd90wsll9anlkrfua38flr",
    "size": 3543,
    "tx_count": 7,
    "output": "84480521968151",
    "fees": "1253244",
    "block_vrf": "vrf_vk1sleujze3zraykllkafvrxggcmpts3hp6zxrpazdkdzp9g07kkehsnmy8ka",
    "previous_block": "c519d70c1d08a9645648fb3cb36b218496b6c3dc342552f57e7c487a10320122",
    "next_block": null,
    "confirmations": 0
}
```

- `submitTx` - `/tx/submit`
- `evaluateTx` - `/utils/txs/evaluate`

# ogmios-datum-cache / Kupo

- GetDatumByHash - `scripts/datum/:datum_hash`
- GetDatumsByHashes - not supported, but it's just a batched version of the above

**Comment by klntsky** [comment]
Blockfrost can help with getting number of confirmations for transaction:

- get Tx block ID by Tx ID
- get number of block confirmations by block ID

**Comment by klntsky** [comment]
This ended up being on Catalyst: https://cardano.ideascale.com/c/idea/420791/

**Comment by klntsky** [comment]
Note: this list is going to be expanded with staking-related endpoints when we merge #1135 
TODO: find if/how we can use blockfrost for that.

**Comment by klntsky** [comment]
@jy14898 how do you know it's using Ogmios?

**Comment by jy14898** [comment]
@klntsky https://docs.blockfrost.io/#tag/Cardano-Utilities/paths/~1utils~1txs~1evaluate/post The response mentions its the same as Ogmios, which to me means with almost certainty they're using ogmios to handle that endpoint

**Comment by klntsky** [comment]
Closing. We will be ready to merge #1260 soon
