### ISSUE TITLE
Consolidate Cardano Nix inputs in a common/shared repo

### ISSUE THREAD

**Issue by bladyjoker** [Plutonomicon/cardano-transaction-lib#534]
Managing revisions of our dependencies is difficult, that's why across MLabs we've settled on a temporary solution to use [github:mlabs-haskell/bot-plutus-interface](https://github.com/mlabs-haskell/bot-plutus-interface) as the canonical source of Nix derivations that are used across projects.

This repo assures that all dependencies are compatible at compilation level and provides one place where the efforts of upgrading library versions take place. It also makes it easy to communicate across projects which `derivation set` is used (essentially bpi revision).

Having this stashed in BPI is not ideal, and we should consider making a special repo with that specific purpose in mind stand alone.

Regardless, we should consider supporting this `mini project` from CTL side as well as we introduced all the flake inputs explicitly which is not ideal.

**Comment by ngua** [comment]
I definitely like the idea of having a public repo for this. Although hopefully this won't be necessary in the end for CTL :)

**Comment by ngua** [comment]
We only need to remove one more endpoint (the hardest one!) then we can remove CTL's server component, so this won't be necessary eventually
