### ISSUE TITLE
UTF8 handling libraries don't fail on invalid UTF8 byte sequences

### ISSUE THREAD

**Issue by bladyjoker** [Plutonomicon/cardano-transaction-lib#544]
CTL uses 2 libraries (for some reason) that handle UTF encodings and both of these libraries implement `decode` such that it never fails. This broke Aeson handling for `TokenName` which is atrocious in its own right.

- purescript-encoding https://github.com/menelaos/purescript-encoding/blob/v0.0.6/src/Data/TextDecoder.js#L5
- purescript-text-encoding https://github.com/AlexaDeWit/purescript-text-encoding/blob/master/src/Data/TextDecoding.js#L25

As @jy14898 mentioned this is simply wrong and the TextDecoder should be instantiated with the `fatal` flag turned on:

```javascript
    var decoder = new TextDecoder("utf-8", {fatal: true});
```
I'm opening this bug to link into a regression test, but we should consider the following as well:

- [ ] Which library to use for text and in specific UTF encodings?
- [ ] Should we open a PR and fix it upstream or make a fork ourselves?

**Comment by ngua** [comment]
Closed by #537
