### ISSUE TITLE
Consolidate and separate FFI APIs under appropriatelly scoped namespace/modules

### ISSUE THREAD

**Issue by bladyjoker** [Plutonomicon/cardano-transaction-lib#548]
cardano-serialization-lib and other js libs are called in CTLs FFI bindings in a scattered manner, which is not ideal as we should strive towards consolidating these APIs under well scoped modules and eventually packages with tested boundaries.

Use this ticket for tracking `FIXME` statements throughout the codebase that indicate this issue.

**Comment by ngua** [comment]
Not only CSL/CML, we also do this in a few other places (e.g. `src/JsWebsocket.js`)

**Comment by klntsky** [comment]
https://github.com/Plutonomicon/cardano-transaction-lib/issues/1116 will make this unneeded
