### ISSUE TITLE
Consolidate node/browser JS library resolution to a single 'entry' module

### ISSUE THREAD

**Issue by bladyjoker** [Plutonomicon/cardano-transaction-lib#549]
CTL `requires` JS libraries across different FFI modules and then handles browser/node incompats such as:

```javascript
let OurTextDecoder;
if (typeof BROWSER_RUNTIME == 'undefined' || !BROWSER_RUNTIME) {
  OurTextDecoder = require('util').TextDecoder;
} else {
  OurTextDecoder = TextDecoder;
}
```

Let's consider if there's a better way of managing this, such that resolution of a each JS library is done at one place and bound to a dictionary that could be perhaps passed to each of the FFI modules.

**Comment by klntsky** [comment]
I'm against this. Resolution is essentially an object property lookup when the code is bundled. Zero runtime overhead. If we pass an object to every JS FFI function, that would be significantly slower and more boilerplate-ish.

**Comment by klntsky** [comment]
Such a  change would not provide any value to anyone.

**Comment by bladyjoker** [comment]
> Such a change would not provide any value to anyone.

I think there's some value to managing this at a single place and thus an easier way to make sure libraries we use have both a nodejs and a browser support. Currently it's not clear whether CTL can run on both platforms, it would require you to check each FFI module to see if they load the appropriate library and do the environment check. To me this is similar to a problem of having unrestricted/uncontained IO everywhere. 

That being said, this seems to be the Purescript FFI way and we should stick to it and honestly, it's not a big deal. We just stumbled on this topic and thought to just make it into an issue and discuss it.
