### ISSUE TITLE
Avoid byte manipulations in PrivateKey decoding

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#554]
`DecodeAeson PrivateKey` instance, introduced in https://github.com/Plutonomicon/cardano-transaction-lib/pull/543, manipulates the byte representation. We should delegate this to CML in the future (CSL's `PrivateKey` does not have `from_bytes`, only `from_normal_bytes`, which accepts the key without CBOR wrapper)

**Comment by jy14898** [comment]
Closing as completed in https://github.com/Plutonomicon/cardano-transaction-lib/pull/607 (and we're not switching to CML)
