### ISSUE TITLE
`mustBeSignedBy` doesn't set the `requiredSigners`

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#559]
Currently, if we use `mustBeSignedBy`, it looks up the provided pkh in a `Map PaymentPubKeyHash PaymentPubKey` in the lookups and then uses the `PaymentPubKey` (if it exists) to calculate the `Ed25519KeyHash` to add to the `requiredSigners`. There's no way currently to provide this lookup however -- this code is still commented out in `Types.ScriptLookups`:
```-- -- | A script lookups value with a payment public key. This can fail because we
-- -- | invoke `payPubKeyHash`.
-- paymentPubKeyM :: forall (a :: Type). PaymentPubKey -> Maybe (ScriptLookups a)
-- paymentPubKeyM ppk = do
--   pkh <- payPubKeyHash ppk
--   pure $ over ScriptLookups
--     _ { paymentPubKeyHashes = singleton pkh ppk }
--     mempty
```

So this will always be empty

What do we want to do about this? We can
- export `paymentPubKey` as a lookup. `paymentPubKeyM` won't work as defined above, that was commented out a long time ago, so it needs to be implemented correctly (in fact we'd probably need several variants of these)
- remove the lookup code altogether, since we can just unwrap the `PubKeyHash` argument to `mustBeSignedBy` and wrap it as a `RequireSigner`. Of course, this is different from Plutus' approach which requires you to provide the `PaymentPubKey`

**Comment by klntsky** [comment]
@ngua this should be closed, right?

**Comment by ngua** [comment]
@klntsky I was thinking we could actually implement the lookups-based approach from Plutus, but we might want to remove lookups entirely in the future. This can be a starting point for that approach :)
