### ISSUE TITLE
Remove `ScriptLookups.paymentPubKeyHashes` or implement lookup

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#569]
Since we don't have a lookup for `paymentPubKey`, #568 directly sets the `requiredSigners` using the provided PKH. This is different from Plutus' implementation, which requires the `paymentPubKey` lookup and makes the `paymentPubKeyHashes` field redundant as there's no lookup that allows users to add to it

We could either
- remove this field
- implement the `paymentPubKey` lookup and bring `mustBeSignedBy` into line with Plutus' constraint

**Comment by klntsky** [comment]
For context: we decided that we go the second route

**Comment by klntsky** [comment]
We're getting rid of lookups
