### ISSUE TITLE
`feeTooSmall` error when submitting a tx with `scriptDataHash` set to `Nothing`

### ISSUE THREAD

**Issue by errfrom** [Plutonomicon/cardano-transaction-lib#570]
After moving the calculation and setting of the script integrity hash to the client, we encountered a problem where we get a `feeTooSmall` error when trying to submit a transaction with `scriptDataHash` set to `Nothing`. 

The current workaround is to explicitly set `scriptIntegrityHash` to `SNothing` on the server:
```Haskell
withScriptIntegrityHash :: C.Tx C.AlonzoEra -> C.Tx C.AlonzoEra
withScriptIntegrityHash transaction@(C.Tx txBodyAlonzo keyWits) =
  case txBodyAlonzo of
    Shelley.ShelleyTxBody era txBody scr sData aux val ->
      case Tx.scriptIntegrityHash txBody of
        SNothing ->
          let txBody' = txBody {Tx.scriptIntegrityHash = SNothing}
               shelleyB = Shelley.ShelleyTxBody era txBody' scr sData aux val
           in C.Tx shelleyB keyWits
        _ -> transaction
```

Steps to reproduce:

1. [Server -> `Api.Handlers` -> `estimateTxFees`] Replace this line 
```Haskell
fee = estimateFee pparams witCount (withScriptIntegrityHash tx')
```
with 
```Haskell
fee = estimateFee pparams witCount tx'
```
2. Run `Examples.Pkh2Pkh`

**Comment by klntsky** [comment]
How can we reproduce it? I suspect it might be fixed by #866
