### ISSUE TITLE
Use `Safe.Coerce.coerce` where possible

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#574]
We're mapping with unwrap/wrap in some places, which representationally is identity. Some cases I found by searching github:

https://github.com/Plutonomicon/cardano-transaction-lib/blob/92a228f7b052da68d6cd41e76f305b575ab76608/src/Wallet/Key.purs#L65
https://github.com/Plutonomicon/cardano-transaction-lib/blob/92a228f7b052da68d6cd41e76f305b575ab76608/src/Contract/Monad.purs#L146
https://github.com/Plutonomicon/cardano-transaction-lib/blob/92a228f7b052da68d6cd41e76f305b575ab76608/src/Types/ScriptLookups.purs#L499
https://github.com/Plutonomicon/cardano-transaction-lib/blob/92a228f7b052da68d6cd41e76f305b575ab76608/src/Contract/Transaction.purs#L188

Eg.
```haskell
local f contract = Contract $ local (dimap wrap unwrap f) (unwrap contract)
-- becomes
local f contract = Contract $ local (coerce f) (unwrap contract)
```

**Comment by klntsky** [comment]
I'm strongly against safe coerce: it makes the code less readable when there are lots of domain newtypes, and the errors become less useful.
