### ISSUE TITLE
Load Plutus scripts from files, instead of hardcoding them

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#579]
The Ask:

Add utility function to load plutus script from file in envelope (`cardano-cli`) format.

Put it in a separate module and indicate that it's nodejs-only.

We are not going to use it for browser runtime, since it's not possible to read files. 

However, we'd like to support the use case when the utility function is used to construct a hardcoded value for PS code. So make sure that `Show` instance is correct.

**Comment by jy14898** [comment]
Closing as this was implemented in https://github.com/Plutonomicon/cardano-transaction-lib/pull/607
