### ISSUE TITLE
Consider adding CTL+plutarch template

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#580]
We can either try adding it optionally to CTL runtime or to ctl-scaffold. TBD

**Comment by ngua** [comment]
We probably don't want to bring in all of Plutarch. The best solution is probably to extend plutus-scaffold as we've discussed in the past

**Comment by L-as** [comment]
This is planned to go into https://github.com/mlabs-haskell/mlabs-tooling.nix .

**Comment by klntsky** [comment]
https://github.com/mlabs-haskell/the-plutus-scaffold
