### ISSUE TITLE
Document how to use CTL runtime for library users

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#592]
We have a section in `doc/development.md`, but nothing in `getting-started.md` points to it. We need to make it apparent that not only CTL developers need to start the runtime, but also library users.

**Comment by zmrocze** [comment]
it points already https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/getting-started.md#other-prerequisites

**Comment by klntsky** [comment]
Thanks @zmrocze
