### ISSUE TITLE
`require` value causing issues with webpack

### ISSUE THREAD

**Issue by ursi** [Plutonomicon/cardano-transaction-lib#593]
https://github.com/Plutonomicon/cardano-transaction-lib/blob/6d47a100781379b54debc801b4f13a21ea182c23/src/Types/ScriptLookups.purs#L454-L455

Since this project is still using PureScript 0.14 (0.15 has switched to ES modules) the fact that this is called require has caused webpack to misbehave. It's not even an exposed module, could it be renamed to something like `require'`?

**Comment by klntsky** [comment]
I suggest `requireValue`
