### ISSUE TITLE
Integrate Ogmios' `local-tx-monitor` mini-protocol

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#594]
https://ogmios.dev/mini-protocols/local-tx-monitor/

We'll need to be pretty careful about integrating this in the most ergonomic way for users

**Comment by klntsky** [comment]
We decided not to give control of the tx monitor protocol to the hands of the users, because it is inherently stateful and we use it to check if we need to replay `submit` calls when they are failing - https://github.com/Plutonomicon/cardano-transaction-lib/pull/870
