### ISSUE TITLE
Support awaiting tx status changes

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#597]
We should support something like `awaitTxConfirmed`/`awaitTxStatusChanged` from Plutus. One way to do this is to query the chain until the transaction hash returns a full transaction. Another way might be to use Ogmios' local tx monitor, although that would mean that we couldn't support this feature for a hypothetical Blockfrost backend

Currently blocked on #30 (or #594 if we want to use the Ogmios approach)

**Comment by klntsky** [comment]
`awaitTxStatusChanged` is currently impossible, because Ogmios does not differentiate between committed state and `TentativelyConfirmed`. @ngua should we close it?

**Comment by ngua** [comment]
Yes I think our support is good enough now
