### ISSUE TITLE
Allow blake2b hashing outside of `Aff` context

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#688]
#520 made it so all blake2b hashing now requires an `Aff` context. It would be ideal if hashing was pure from the perspective of users. Hopefully we can figure out a way to load the WASM in JS without requiring `Aff` for the FFI bindings. Would top-level `await` work?

**Comment by klntsky** [comment]
> Would top-level await work?

No.


```
       > Module parse failed: Cannot use keyword 'await' outside an async function (25594:2)
       > You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
       > |   }
       > |
       > >   await new Promise(
       > |       (resolve, reject) =>
       > |           Blake2bWasm.ready(error => {
       >  @ ./examples/index.js 8:0-22
```

**Comment by klntsky** [comment]
Reposting myself from slack:

The library loads wasm asynchronously via a call to `blake2b.ready`. We can do something like:

  - call ready on module initialization
  -  call ready on contract initialization and wait for promise resolution
  -  expose ready as Aff function users need to wait on if they get errors when trying to use hashing before initialization
  -  make the hashing functions pure (throw exception in case wasm hasn't been loaded yet, explaining that the call should be delayed until ready)
