### ISSUE TITLE
Use proper language parser for explicit imports  check

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#704]
From https://github.com/Plutonomicon/cardano-transaction-lib/pull/703#issuecomment-1178781769: 

> In the future we could look into using https://github.com/natefaubion/purescript-language-cst-parser to re-write this check. I don't see it taking longer than a days work, and imo it's better than forking purs-tidy and having to keep up with their changes.

**Comment by jy14898** [comment]
This could also be a starting point to introduce further checks like ensuring all universally quantified type variables have an explicit kind, etc

**Comment by ngua** [comment]
I guess the plan is to write a PS linter then? This is something I've missed quite a bit

**Comment by Luis-omega** [comment]
I would like to write something like that. Since this task is of lower priority, maybe doing little advances between tasks?

**Comment by klntsky** [comment]
@Luis-omega it is not needed as my grep-based solution (`make check-explicit-exports`) performs reasonably well as time has shown

**Comment by Luis-omega** [comment]
All right, should we close this ticket then?
