### ISSUE TITLE
Make the flake overlay actually use the passed nixpkgs instance instead of using own instance

### ISSUE THREAD

**Issue by yusdacra** [Plutonomicon/cardano-transaction-lib#706]
The Nix overlay provided seems to be not using the nixpkgs instance passed to the overlay in some cases, but instead import it's own nixpkgs instance which causes issues when used downstream and also slows evaluation. Specifically:

https://github.com/Plutonomicon/cardano-transaction-lib/blob/be5ff37abe86fa44a1c7c3aea8bc9eeda4039125/flake.nix#L146-L158

here, the `buildCtlRuntime` and `launchCtlRuntime` will both call `nixpkgsFor` which uses the flake's own nixpkgs input to import a new nixpkgs instance, instead of using the nixpkgs instance passed to the overlay (`final` / `prev`). Other defined attributes also do this with the exception of `easy-ps` and `purescriptProject`. This causes issues in downstream projects because the expected behavior is that the overlay will use the nixpkgs instance it was passed, not import other nixpkgs instances (which may or may not be in sync, which is the main cause of problems).

**Comment by klntsky** [comment]
This may be a solution: https://github.com/Plutonomicon/cardano-transaction-lib/tree/brian/tryYusdacraFix
