### ISSUE TITLE
firstBlock config seems to be ignored

### ISSUE THREAD

**Issue by Geometer1729** [Plutonomicon/cardano-transaction-lib#714]
When runing `nix run .#ctl-runtime` in `407fde2f522feac4b9c86a8579b6b3cb0cdfb70f` (currently the newest commit on develop) the ogmious datum cache starts at slot 0 rather than the slot specified in firstBlock.

**Comment by ngua** [comment]
I mentioned this on Discord as well, but are you passing the corresponding block hash for the selected slot?

**Comment by Geometer1729** [comment]
Yes. You can also reproduce this with the first block config as it is in ctl.
