### ISSUE TITLE
Remove user-defined configs and `Row Type` `Contract` parameter.

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#734]
Reasons:

- The library does not necessitates using the parameter, and Slack survey exposed little interest in it.
- It's not hard to provide extra parameters to the contract with ReaderT or simply via an extra argument.
- the intention was to keep extra configs in Contract, but it's unlikely that Contract is going to be used to manage user application configs/state.

So, it's tangential to the main goal of the library.

The change should happen in v3.

**Comment by adamczykm** [comment]
Assuming I'm implementing a library using Contract monad for its functionality and I want to extend the reader environment, what will be the simplest / most convenient way to do it if we remove 'r' parameter?

**Comment by klntsky** [comment]
@adamczykm  `ReaderT`.

**Comment by adamczykm** [comment]
Wrapping it in another readert?

**Comment by klntsky** [comment]
Yes, we should not assume that our users need some specific monadic stack in their applications. It's up to them to decide how to extend the Contract (or not to extend it at all).
