### ISSUE TITLE
CIP 25 Metadata not following spec

### ISSUE THREAD

**Issue by rynoV** [Plutonomicon/cardano-transaction-lib#752]
There's two issues that I can see:

**Issue 1**: When CTL adds metadata to transactions with `setTxMetadata` it seems to add `0x` before byte strings (I'm guessing this is just the cardano metadata standard for byte strings). I think this might be an issue with [CIP25](https://cips.cardano.org/cips/cip25/) and CTL's support for it: the spec requires the `asset_name` and `policy_id` to be "utf-8 encoded and in text format" for version 1, and CTL includes them as raw bytes (and CTL uses version 1 by default because the `version` property is not included). An example of metadata created by CTL using `setTxMetadata` with `Cip25Metadata`:

```json
[
  {
    "721": {
      "0xda90b3ed7f25fcb4f43794e568d8397afe05de82399d78e27a6c0fe8": {
        "0xabcdef": {
          "description": [
            "Allium",
            "Seabug Testing"
          ],
          "files": [],
          "image": [
            "ipfs://k2cwuee3arxg398hwxx6c0iferxitu126xntuzg8t765oo020h5y6npn"
          ],
          "name": "0xabcdef"
        }
      }
    }
  }
]
```

I think this would be valid if `"version": 2` were added because version 2 uses raw bytes for `policy_id` and `asset_name`. For reference this is how cardanoscan renders that metadata:

![2022-07-18-110712_807x400_scrot](https://user-images.githubusercontent.com/35615725/179565123-96011898-0343-4367-a8f6-351c8f8fd76e.png)

**Issue 2**: The `name` field is supposed to be a string but is also included as raw bytes (with the `0x` prefix) by CTL (it seems to just use the token name). See the previous example.

**Comment by klntsky** [comment]
`assetName` is defined as `TokenName` and `EncodeAeson` instance for `TokenName` explicitly adds `0x`.

See this PR for context: https://github.com/Plutonomicon/cardano-transaction-lib/pull/537

The solution I see is to newtype `TokenName` as `Cip25TokenName` and provide an instance that does not add the `0x` prefix.
