### ISSUE TITLE
`window.cardano.gerowallet` is `undefined`

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#755]
On `localhost` at least, the Gero wallet browser extension doesn't appear to be injecting the JS API. This isn't a CTL bug, but we should have somewhere to discuss this since there's no open-source repository for the extension

To reproduce:

- run any CTL contract with `mkGeroWalletAff`
- serve the JS bundle with `webpack-dev-server` (e.g. `npm run dev`)
- visit `localhost:4008`

`window.cardano.gerowallet` is also undefined when using the dev console directly

**Comment by klntsky** [comment]
Link to Gero version before the change:

https://github.com/Plutonomicon/cardano-transaction-lib/blob/mike/e2e-simple/test-data/chrome-extensions/gero_testnet_1.10.0_0.crx

I think this guide may be useful to prevent extension updates: https://gist.github.com/juniorcesarabreu/115a4f5141cd1a841119c511c4c66d3f

**Comment by cyprusdonkey** [comment]
Hi @ngua I believe the issue is with the specific version the manifest is not defined to allow http://*/* so that is why you can not see it in localhost. Having said that, there is an offline version we have started working on to accommodate the changes required for Vasil. Its a work in progress but it would be great if you could test it so we can cover as many cases as possible. I can either provide an offline installer or we can push it live in 2-3 days once the current changes have been implemented.

**Comment by klntsky** [comment]
> I can either provide an offline installer or we can push it live in 2-3 days once the current changes have been implemented

@cyprusdonkey that would be great! Where can we get the installer or is the new build already available?

**Comment by cyprusdonkey** [comment]
Hi @klntsky I will ping you as soon as its available on Chrome store.

**Comment by cyprusdonkey** [comment]
https://chrome.google.com/webstore/detail/iifeegfcfhlhhnilhfoeihllenamcfgc here is the latest testnet version, http://*/* should be open for local testing. Let me know if any issues. Thank you

**Comment by ngua** [comment]
Thanks @cyprusdonkey!

**Comment by cyprusdonkey** [comment]
Hi @ngua circling back on this, has the issue been resolved? Need any further assistance? What was the outcome of the compatibility evaluation? Thank you

**Comment by klntsky** [comment]
@cyprusdonkey Hi, which testnet is this extension for: `preview`, `preprod`, or the legacy one?

We are using the build for preview that Shawn sent to us, and `cardano.gerowallet` is still `undefined` there - probably the changes to use preview were made to the older version?

**Comment by klntsky** [comment]
They fixed it
