### ISSUE TITLE
Check CostModels serialisation doesn't care about the order CostModels are inserted in, for mixed language transactions

### ISSUE THREAD

**Issue by jy14898** [Plutonomicon/cardano-transaction-lib#764]
https://github.com/Plutonomicon/cardano-transaction-lib/blob/6ea2caee587cddf7835f797eecbf9e61d304bc1e/src/Serialization.purs#L830-L841

**Comment by klntsky** [comment]
It does not. Source: ~~trust me~~ `CostModel` is basically a specialized Map, we haven't had any issues with any of similar CSL types. See also https://github.com/input-output-hk/cardano-ledger/blob/14e1bcc89e275600efb8b66c7cefeebfb1764204/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L312
