### ISSUE TITLE
Add chromium, tar and unzip to dev shell

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#787]
They are needed for E2E tests. We should add chromium as an optional dependency (should be explicitly enabled).

**Comment by epiro-ps** [comment]
Not sure if this is worthy of a second issue but could we also add some documentation on how to run the E2E tests?

**Comment by klntsky** [comment]
@epiro-ps I'm OMW (on my way) to create one

**Comment by klntsky** [comment]
@epiro-ps https://github.com/Plutonomicon/cardano-transaction-lib/issues/789
