### ISSUE TITLE
Simplify multisign functionality

### ISSUE THREAD

**Issue by blamario** [Plutonomicon/cardano-transaction-lib#8]
CIP-0030 specifies a [signTx](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0030#apisigntxtx-cbortransaction-partialsign-bool--false-promisecbortransaction_witness_set) function that can add a partial set of signatures to a transaction.

As argued [here](https://mlabs.slab.com/posts/transaction-multisign-procedure-i9r7eeyp), this functionality would be easier to use if the function took a partially-signed transaction and returned some-more-signed transaction.

**Comment by Benjmhart** [comment]
just to expand on the workflow, ideally what we would have is:

1. user 1 generates a transaction and signs it.
2. user 1 sends a serialized transaction with partial signature to user 2
3. user 2 signs the tx
4. repeat as above for n users
5. submit the transaction

**Comment by nrutledge** [comment]
This might complicate things with race conditions, etc., but perhaps it would be better to persist the transaction temporarily and make it available to all parties for signing. 

Passing along to each party as a serial process seems like it would have the following issues:
- If trying to get a majority of some group to sign a TX, a signer may not know the appropriate next signer to send to 
- For large groups, this process would be unnecessarily slow (e.g., user 1 sends to user 2 who isn't available for days, but user3 is ready right now to sign)

This may be a dumb question, but is it possible to have multiple copies of the TX signed by different parties and then merge into a single transaction?

**Comment by blamario** [comment]
Yes, merging of transaction signatures should be possible on top of Plutus API. I'm just unclear on what kind of communication infrastructure would also be needed to make this process easy. The minimum would be to generalize the above process to

1. user 1 generates a transaction and signs it
2. user 1 sends a serialized transaction with partial signature to all users 2..n
3. user i signs the tx and sends back to user 1
4. repeat step 3 for n-1 users
5. user 1 merges the partially-signed transactions into a single fully-signed transaction
6. user 1 submits the transaction

But that seems to put a heavy burden on user #1. Perhaps a future project could be to create a SignHub.com to handle the process

0. users 1..n register their public keys and notification handles
1. user 1 generates a transaction and signs it
2. user 1 uploads the transaction to SignHub.com
3. SignHub notifies all expected signatories
4. user i logs into SignHub and signs the tx
5. repeat step 4 for n-1 users
6. when all signatures are ready, SignHub merges them and
    a. notifies user 1 to submit the transaction or
    b. submits the transaction itself

**Comment by Benjmhart** [comment]
i think this is blocked until we get transactions with single-signatures working in the browser.

**Comment by ngua** [comment]
> This may be a dumb question, but is it possible to have multiple copies of the TX signed by different parties and then merge into a single transaction?

I think this might be possible. When all parties have signed we might be able to just merge the vkey witnesses from the tx copies into a single witness set

**Comment by blamario** [comment]
https://github.com/input-output-hk/cardano-node/pull/3549

**Comment by maciej-bendkowski** [comment]
Could we please increase the priority of this issue? I have a use-case which would benefit from a simple two key co-signing feature. User A creates a transaction, signs it, sends it to user B, who then signs it and submits it to the ledger.

**Comment by klntsky** [comment]
@maciej-bendkowski we support multisign now. Can we close this issue?

**Comment by maciej-bendkowski** [comment]
> @maciej-bendkowski we support multisign now. Can we close this issue?

Sure, thanks!
