### ISSUE TITLE
Don't use infix tuple constructor in `ToMetadata.purs`

### ISSUE THREAD

**Issue by rynoV** [Plutonomicon/cardano-transaction-lib#813]
I've been using [this branch](https://github.com/Plutonomicon/cardano-transaction-lib/tree/calum/metadata-invalid-char-fix) of CTL for a while because ToMetadata.purs 's use of the infix tuple constructor causes a syntax error in the output javascript file (the `/\` doesn't get escaped properly when it's put in string literals).

Wasn't really sure if I should make a PR since this isn't exactly a CTL issue, but it's annoying to have to maintain my own branch. The diff is [here](https://github.com/Plutonomicon/cardano-transaction-lib/compare/develop...calum/metadata-invalid-char-fix#diff-6a2594f7eae5a5b91eef5c385427b664eec4a3af84c9f8a1fc55b3ae9e0191a9), let me know if you're okay with merging this and I'll make a PR

**Comment by rynoV** [comment]
#633 addresses this issue

**Comment by klntsky** [comment]
Closed by https://github.com/Plutonomicon/cardano-transaction-lib/pull/822
