### ISSUE TITLE
Move all internal/non-`Contract` modules to clearly delineated namespace

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#820]
Our current module naming scheme needs improvement. It 
- is more appropriate for applications (e.g. `Types.*`)
- occupies too much of the top-level namespace
- leads to unclear and confusing documentation
- doesn't reinforce the fact that users shouldn't import non-`Contract` modules

**All** internal/non-`Contract` modules should be moved to a clearly delineated internal namespace. I propose `Ctl.Internal.*`. This includes all of our examples, test, etc...

**Comment by jy14898** [comment]
I've thought about this previously, the absolute way to ensure users don't import non-contract modules would be to have two separate purescript packages. This way, if a user imports something from the internal side, they'll get an error from spago saying a module from our internal package was imported but not listed in their spago.dhall.

**Comment by ngua** [comment]
@jy14898 We'd still need to do the namespacing thing, and at that point I'm not sure if it would be worth the extra effort of adding a separate project

**Comment by jy14898** [comment]
> @jy14898 We'd still need to do the namespacing thing, and at that point I'm not sure if it would be worth the extra effort of adding a separate project

Yeah I didn't suggest it as an alternative amount of work, but extra.

Unfortunately `purescript-language-server` doesn't respect packages, so our internal types would still appear in code completion/suggestions
