### ISSUE TITLE
Remove `lookups`

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#843]
In the distant future I think we can remove lookups and replace them with extra arguments to constraints.

We need to:

1. Find what exactly motivated lookups existence in plutus
2. See if it applies to us
3. If not, introduce a better interface. We can provide a compatibility layer that will translate old constraints and lookups to "new" constraints.

**Comment by L-as** [comment]
This has been my biggest pet peeve wrt. CTL. The original design isn't very logical, and was likely the result of a deadline having to be met (as with most of Plutus).
AFAICT there isn't any good reason.
However, I suggest making an issue on plutus-apps where you suggest removing them. That will likely get a response from more knowledgeable people.

**Comment by klntsky** [comment]
https://github.com/input-output-hk/plutus-apps/issues/674

**Comment by klntsky** [comment]
I think we can do it as part of v4

**Comment by klntsky** [comment]
Here's a plan how we can simplify the interface:

```
  , generalise -- typed validators are not needed
  , mintingPolicy -- can be moved to constraints
  , mintingPolicyM -- not needed
  , datum -- can be moved to constraints
  , validator -- can be moved to constraints
  , validatorM -- maybe variant is not needed
  , ownPaymentPubKeyHash -- not needed, can be derived from Contract
  , ownPaymentPubKeyHashM -- maybe variant is not needed
  , ownStakePubKeyHash -- not needed, can be derived from Contract
  , ownStakePubKeyHashM -- maybe variant is not needed
  , typedValidatorLookups -- typed validators are not needed
  , typedValidatorLookupsM -- maybe variant is not needed
  , unspentOutputs -- can be provided as constraint
  , unspentOutputsM -- maybe variant is not needed
```

**Comment by klarkc** [comment]
I believe we should keep using the pair constraints/lookups for now, as they reflect the validation we use on-chain in the off-chain code. Additionally, there is the added benefit that if we ever write UPLC with PureScript, the API will be plug-and-play. Therefore, it might be premature to remove lookups at this time. Maybe another approach would be to have two different APIs (Plutus - isomorphic / Off-chain-only).

**Comment by klntsky** [comment]
> as they reflect the validation we use on-chain in the off-chain code

In practice, they don't. Moreover, our constraints are different from Plutus, and some of them don't make any sense on-chain.

> Additionally, there is the added benefit that if we ever write UPLC with PureScript, the API will be plug-and-play

It has never been a goal of CTL, we didn't even consider it.

**Comment by klntsky** [comment]
https://github.com/Plutonomicon/cardano-transaction-lib/pull/1628
