### ISSUE TITLE
Make ctl-server optional

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#872]
We should allow to NOT start `ctl-server`. 

# Changes to Contract

`applyArgs` should fail on connection error with a meaningful error message, showing how to enable `ctl-server`

# Changes to Plutip

We should add a `PlutipConfig` parameter that controls `ctl-server` availability.

# Changes to nix

`ctl-server` should be removed from `overlays.runtime` and put into its own overlay

# Changes to docs

We should make it clear that `ctl-server` is optional. Show how to use it with changes in Nix.

**Comment by ngua** [comment]
For the Nix changes, we should also make it optional in the runtime

**Comment by ngua** [comment]
I was only going to take care of the Nix part but I might as well do the PS part too
