### ISSUE TITLE
Bump node to v1.35.3

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#898]
Need to bump to v1.35.3 and 5.5.4, respectively. The latter needs to be done our fork of Ogmios

**Comment by ngua** [comment]
The Ogmios changes are done on our fork, but it looks like node v1.35.3 isn't syncing with the public testnet. Will keep and eye on that and post an update when applicable

**Comment by ngua** [comment]
The Ogmios changes should be a part of #906

**Comment by klntsky** [comment]
Done
