### ISSUE TITLE
Add E2E test support for Flint wallet

### ISSUE THREAD

**Issue by firefrorefiddle** [Plutonomicon/cardano-transaction-lib#909]

**Comment by uhbif19** [comment]
@klntsky Looks like Flint works with old testnet. Cuz I see ADA on preprod/preview network for the addresses in blockchain explorer, but Flint Wallet seems no ADA (and shows link for address in old testnet)

**Comment by klntsky** [comment]
@uhbif19 yes, please request preview support.

**Comment by uhbif19** [comment]
@klntsky Looks like you already asked about that in Discord. I pinged on updates.

https://discord.com/channels/857911582972968981/881954687211933696/threads/1019691729865146519

**Comment by klntsky** [comment]
We will only add wallet support to the e2e test suite if funded by someone.
