### ISSUE TITLE
[Metatask] Babbage bugs

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#913]
I'm going to make this a combined task so individual ones won't get lost in open issues. We can split them into individual ones later but I want a single place to collate them

We have some projects that are really using the Babbage features now, but they've run into some issues

- [x] #916

- [x] The signature verification costs on Vasil testnets have been raised to an extreme value so they are not used. This causes the following problem:
  ```
    Error: (AtKey "costModels" (AtKey "plutus:v2" (AtKey "verifyEcdsaSecp256k1Signature-cpu-arguments" (TypeMismatch "Couldn't parse to integral: 20000000000"))))
  ```
  Likely solution: change the type of `verifyEcdsaSecp256k1Signature-cpu-arguments` to `BigInt`. This is serializable using `Types.Int.Int`, verified with `lib.Int.new(lib.BigNum.from_str("20000000000"))` in the NodeJS repl. [this PR](https://github.com/Plutonomicon/cardano-transaction-lib/pull/912) has implemented the changes (untested)

- [x] Testnets launched via Plutip are currently missing `PlutusV2` cost models. We need to see if the configuration Plutip uses to launch the node needs to be updated. We could also make the `costModels` field hold `Maybe CostModels` so parsing will at least still succeed

- [x] Our `TextEnvelope` decoder doesn't recognize `PlutusScriptV2` as a `type`, making it impossible to conveniently load scripts with Babbage/`PlutusV2` features

  Likely solution: [this PR](https://github.com/Plutonomicon/cardano-transaction-lib/pull/912)

**Comment by ngua** [comment]
It looks like the cost models issue was solved by a previous CSL upgrade. Everything else listed in this issue has been fixed

**Comment by gege251** [comment]
Nice work everyone, thank you for the quick response!
