### ISSUE TITLE
Add `PlutusV2` examples on `babbage`

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-transaction-lib#922]
We should add some example contracts that contain `PlutusV2` features

https://github.com/input-output-hk/Vasil-testnet

 - [x] [Collateral return](https://github.com/Plutonomicon/cardano-transaction-lib/pull/947)
Consume a utxo whose value is larger than needed, and return the remainder as change. Also test non-ada value being returned - this might require changes elsewhere.
 - [x] [Reference input](https://github.com/Plutonomicon/cardano-transaction-lib/pull/946)
 - [x] [Reference script](https://github.com/Plutonomicon/cardano-transaction-lib/pull/946)
 - [x] [Inline datum](https://github.com/Plutonomicon/cardano-transaction-lib/pull/931)
 - [ ] (optional) Secp256k1 functions used in a script. Plutip-only at this point

**Comment by jy14898** [comment]
Completed
