### ISSUE TITLE
Handling inline datums when parsing TransactionOutputs from Ogmios

### ISSUE THREAD

**Issue by gege251** [Plutonomicon/cardano-transaction-lib#928]
Ogmios seems to correctly handle inline datums, but they disappear in the CTL parsing step:
> DEBUG] 2022-08-20T19:14:51.337Z message: {"type":"jsonwsp/response","version":"1.0","servicename":"ogmios","methodname":"Query","result":[[{"txId":"425a27a6e4891ae515a6a956cc34ec450e2a65f2933b57d6f3a3acfd179d4d9e","index":1},{"address":"addr_test1wqcvsw2rdp62d79d873umw034uyer0p8k7et9y28623v0xss3tp02","value":{"coins":1340410,"assets":{}},"datumHash":null,"datum":"d8799f46616162626363466161626263634661616262636346616162626363d8799fd8799f5820af2b7df401bf2c03a25151dcf2e954482d5b8cc8ddde467e3ec721e78fc71a3cff00ff581c0f45aaf1b2959db6e5ff94dbb1f823bf257680c3c723ac2d49f97546ff","script":null}]],"reflection":"Query-sktwi1zlgl72a55ja"}

When doing logInfo' $ show utxos

> [INFO] 2022-08-20T19:14:51.374Z (fromFoldable [(Tuple (TransactionInput { index: 1u, transactionId: (TransactionHash (hexToByteArrayUnsafe "425a27a6e4891ae515a6a956cc34ec450e2a65f2933b57d6f3a3acfd179d4d9e")) }) (TransactionOutput { address: (Address { addressCredential: (ScriptCredential (ValidatorHash (ScriptHash 30c839436874a6f8ad3fa3cdb9f1af0991bc27b7b2b29147d2a2c79a))), addressStakingCredential: Nothing }), amount: (PlutusValue (Map [(Tuple (CurrencySymbol (hexToByteArrayUnsafe "")) (Map [(Tuple (TokenName (hexToRawBytesUnsafe "")) fromString "1340410")]))])), datum: NoOutputDatum, referenceScript: Nothing }))])

**Comment by jy14898** [comment]
Merged
