### ISSUE TITLE
Switch to pre-prod

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#942]
> It appears that most of the ecosystem will be switching to `preprod` as the new default testnet network (it's probably a good thing since it will be more stable). But `preprod` is configured the same as `mainnet` -- meaning neither of the two stages in the Vasil hardfork have happened yet. Since we made changes to be Vasil compliant, switching to `preprod` now at the very least breaks our protocol parameters parsing and corresponding Ogmios tests (recall that Ogmios encodes things different depending on the era).

**Comment by ngua** [comment]
Duplicate of #923
