### ISSUE TITLE
Test slot <-> POSIX time conversion without relying on network state

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#945]
We disabled them during transition from `testnet` to `preprod` networks.

**Comment by Luis-omega** [comment]
Isn't this solved already by this https://github.com/Plutonomicon/cardano-transaction-lib/blob/80ae96046fcb7f855a5093e39848499c27fcaac3/test/Unit.purs#L68  and this https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/test/Types/Interval.purs ?

**Comment by jy14898** [comment]
The issue is to undo the `skip` after either adjusting the specific posix times + slots to the current network values, or by generating them based off of the era summaries and system start. Ideally the latter
