### ISSUE TITLE
Provide testing utilities

### ISSUE THREAD

**Issue by rynoV** [Plutonomicon/cardano-transaction-lib#948]
I've been writing CTL tests for Seabug, and I ended up writing a small utility library that I think could be generally useful for CTL tests. I think there's a lot of functions that anyone testing with CTL will end up copy pasting to their projects, especially basics like `assertContract`.

The utilities are unpolished right now, but it could serve as a good starting point for a CTL testing library. The utilities start on [this line](https://github.com/mlabs-haskell/seabug-contracts/blob/81a19140ff1b613cdcba4498c2578ad51b7e9206/test/Contract/Util.purs#L218), and an example test suite that uses them (and that they were built for) can be found [here](https://github.com/mlabs-haskell/seabug-contracts/blob/81a19140ff1b613cdcba4498c2578ad51b7e9206/test/Contract/Buy.purs#L222). Here's some explanation/notes around the utilities:

-   Some principles around the utilities:
    -   `check*` functions perform a check and return the result of the check
    -   `assert*` functions perform a check and fail the test if the check fails
    -   We aim for a test suite that looks declaritive
        -   Convenience of writing tests is prioritized over the speed of the tests
        -   For example, lots of utilities make queries whose results could be reused (e.g. `utxosAt`), but reusing these results would clutter assertions with extra variables and add extra arguments to utilities
        -   In our test suite at least, the lack of query reuse has not had a big effect on the test speed. Queries like `utxosAt` and `getTxByHash` and `getDatumByHash` are fairly quick in the CTL test environment
-   A key class is `WrappingAssertion` which has instances for the various function types that can be used for making assertions about a contract, as well as collections of these functions
    -   The key idea behind this class is the composition of assertions: the class ensures that the result of the contract-under-test (CUT) is passed to all assertions
        -   To use the class, it's recommended that a record is used that stores all the data for the result of the test (`PostBuyTestData` in the example tests)
    -   Once the CUT is written and its result is collected into a single value, one runs it with `wrapAndAssert` or `withAssertions`, and provides a collection of assertions about the contract
    -   `ContractWrapAssertion` is the most powerful type of assertion, it can choose when the CUT is run
        -   It's possible to make an invalid inhabitant of this type, the assertion is only supposed to run the CUT once
            -   Disallowing this would make it more inconvenient to make this type of assertion, not sure if it's worthwhile
        -   This type of assertion for example allows to generalize assertions about the change in value at an address caused by the CUT (`checkBalanceChangeAtAddr` does this)
    -   There are other types of assertions that are just for convenience
-   A good feature would be to have functionality to accumulate failures then fail, instead of exiting on the first failure
    -   I'm pretty sure this would require a custom monad though

**Comment by klntsky** [comment]
This is good, we can cherry-pick functions to something like `Contract.Test.Utils`
