### ISSUE TITLE
Add remainging CIP-30 methods and a check for networkId

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#974]
There are a few CIP-30 methods missing in CTL (because we don't use them).

They should be provided as `Contract` methods.

```
api.getNetworkId(): Promise\<number> -- should throw with KeyWallet
api.getUnusedAddresses(): Promise\<Address[]>  -- should throw with KeyWallet
api.getChangeAddress(): Promise\<Address>  -- should return the main address with KeyWallet
api.getRewardAddresses(): Promise\<Address[]> -- should return the main address with KeyWallet
api.signData(addr: Address, payload: Bytes): Promise\<DataSignature>
```

These should be provided as `Aff` or `Effect`

```
cardano.{walletName}.isEnabled(): Promise\<bool>
cardano.{walletName}.apiVersion: String
cardano.{walletName}.name: String
cardano.{walletName}.icon: String 
```

Also, when CIP-30 wallet is specified in WalletSpec, add a check that NetworkId is the same as the one provided in the config. Throw an informative error message if not.

**Comment by Luis-omega** [comment]
I haven't read cip 30 or know how to do this but I would like to take it and do it in parallel with my current task in ODC, since this is an enhancement I guess this wouldn't be a problem, but I want to ask before I take it.

**Comment by klntsky** [comment]
@Luis-omega feel free to!

**Comment by Luis-omega** [comment]
With the introduction of the new Cardano networks replacing testnet, cip30 is outdated, at least in the part of `getNetworkId` : 

```
api.getNetworkId(): Promise\
Errors: APIError

Returns the network id of the currently connected account. 0 is testnet and 1 is mainnet but other networks can possibly be returned by wallets. Those other network ID values are not governed by this document. This result will stay the same unless the connected account has changed.
```

I don't know what's the current approach to this, but I gonna research it in the wallets prs in CTL.

**Comment by klntsky** [comment]
@Luis-omega 

> cip30 is outdated

No, it's not. Network ID is not network magic. Testnet is both preprod and preview. mainnet is mainnet. It affects bech32 prefixes in addresses, which are the same for any testnet (`addr_test`)

**Comment by Luis-omega** [comment]
That explains why I can't find the difference anywhere. Thanks
