### ISSUE TITLE
Update ODC

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#979]
Tx-by-hash API endpoint changed the way Txs are encoded.

**Comment by Luis-omega** [comment]
Related ODC issue https://github.com/mlabs-haskell/ogmios-datum-cache/issues/118

I could try to do it, but I haven't taken it before since I don't know how to decode a CBOR base64, that would slow me down a little.

**Comment by klntsky** [comment]
@Luis-omega 
We have `Base64` module

**Comment by Luis-omega** [comment]
I will try it then.
