### ISSUE TITLE
`ctl-plutip-test` check is green with failing tests 

### ISSUE THREAD

**Issue by errfrom** [Plutonomicon/cardano-transaction-lib#983]

**Comment by klntsky** [comment]
Example?

**Comment by errfrom** [comment]
@klntsky https://ci.staging.mlabs.city/build/10021#tabs-buildsteps

**Comment by klntsky** [comment]
This is because `exit = false` in test config.

**Comment by jy14898** [comment]
We can use `runSpecT` instead of `runSpec'` to let us inspect post-test whether any failed, and exit non-successfully. That, or have two 'modes' of running the plutip tests, one for integration that fails fast, and one for development which runs as many as possible
