### ISSUE TITLE
Reorganize Envelope API 

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#988]
I think we should remove `Contract.TextEnvelope` because the API is not very type-safe. 

We should provide domain-specific type-safe functions instead for each type we can load from an envelope.

We should add functions for:
- [x] loading from an envelope file (by path) (done in `Contract.Wallet.KeyFile`)
- [x] envelope file contents as string (done in this PR - https://github.com/Plutonomicon/cardano-transaction-lib/pull/944)
- [x] from a cbor hex string extracted from an envelope, with a CBOR prefix, e.g. `5820f1063db3d8a6dde42...` - (for stake and payment private keys)

**Comment by uhbif19** [comment]
@klntsky As far as I understand, there was another task in this issue that we discussed in the onboarding meeting not mentioned here. I thought it meant to inline `TextEnvelopeType` in `Contact.textEnvelopeBytes` - but I looked at the code and don't get why one should need that. Am I understanding task correctly?

**Comment by klntsky** [comment]
@uhbif19 I mean, we need specialized functions for every enum variant of TextEnvelopeType - e.g.

`plutusScriptV1FromEnvelope :: Aeson -> Maybe PlutusScript`

**Comment by uhbif19** [comment]
@klntsky @errfrom Should not this be closed?

**Comment by klntsky** [comment]
@uhbif19 Yes
