### ISSUE TITLE
Investigate what happens when we try to spend collateral

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-transaction-lib#993]
Using `mustSpendPubKeyOutput` on the result of `getCollateral` call makes no sense, we should check what happens and if the error message is clear enough.

This comes from a discussion with our users.

Ideally we should provide an informative error message during constraints evaluation

**Comment by jy14898** [comment]
How does this make no sense? In theory, any input of the transaction can be collateral, because they're consumed mutually exclusively. Either the tx passes phase 2 and the inputs are used normally, or it fails and the inputs may be used as collateral - there's no double spending

**Comment by klntsky** [comment]
It makes no sense if a script is used. If we spend the collateral, the validator can't run. And it may not be obvious, why. I didn't check the exact error message yet.

**Comment by jy14898** [comment]
I have a feeling if built/submitted by cardano-cli, it would be able to run. I haven't tested it though. I think CIP30 wallets might not allow it because of the special treatment of collateral.

> It makes no sense if a script is used. If we spend the collateral, the validator can't run.

I've found a source that says it's fine:

> The collateral inputs get removed from the ledger UTXO only if any script fails phase-2 validation. If all scripts pass, the specified transaction fee amount gets collected, as in previous eras. In particular, the amount comes from the regular, non-collateral inputs, and the collateral inputs are simply ignored. And, good news! It is permitted to use the same inputs as both collateral and regular, since only one of the two sets ever gets removed from the UTXO.
\- https://iohk.io/en/blog/posts/2021/09/07/no-surprises-transaction-validation-part-2/

**Comment by jy14898** [comment]
Also in the alonzo changes pdf

**Comment by klntsky** [comment]
Strange. I've got a report stating that there was an error in this scenario from one of our users. Let's close then.
